#!/usr/bin/env python3
"""MobilityNebula MEOS-operator generator.

Given a JSON descriptor list of MEOS scalar functions to wrap as
NebulaStream operators, emits the 4 pipeline-layer C++ files per
function (logical .hpp/.cpp + physical .hpp/.cpp) following the
established style of the existing hand-written operators (e.g.
TemporalEDWithinGeometryLogicalFunction).

Also emits to stderr:
- The parser-dispatch snippet to paste into
  nes-sql-parser/src/AntlrSQLQueryPlanCreator.cpp
- The grammar snippet to paste into nes-sql-parser/AntlrSQL.g4
- The CMakeLists snippets to paste into the respective
  CMakeLists.txt files

The CMakeLists / parser / grammar are NOT auto-modified — manual paste
keeps the generator idempotent and prevents silent corruption on
regeneration.

Usage:
    python3 codegen_nebula.py --input codegen_input.example.json \\
                              --output-root /path/to/MobilityNebula
"""
import argparse
import json
import sys
from pathlib import Path

# ===========================================================================
# Templates (mirror the hand-written TemporalEDWithinGeometry style 1:1).
# ===========================================================================

LOGICAL_HPP_TEMPLATE = """\
/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Functions/LogicalFunction.hpp>
#include <string_view>
#include <utility>
#include <vector>

namespace NES {{

/**
 * @brief {comment_one_liner}
 *
 * Generated by tools/codegen/codegen_nebula.py from the MEOS function
 * `{meos_call}`. Per-event scalar operator following the
 * TemporalEDWithinGeometry pattern.
 */
class {nebula_name}LogicalFunction : public LogicalFunctionConcept {{
public:
    static constexpr std::string_view NAME = "{nebula_name}";

    {nebula_name}LogicalFunction({ctor_logical_args});

    DataType getDataType() const override;
    LogicalFunction withDataType(const DataType& dataType) const override;
    std::vector<LogicalFunction> getChildren() const override;
    LogicalFunction withChildren(const std::vector<LogicalFunction>& children) const override;
    std::string_view getType() const override;
    bool operator==(const LogicalFunctionConcept& rhs) const override;
    std::string explain(ExplainVerbosity verbosity) const override;
    LogicalFunction withInferredDataType(const Schema& schema) const override;
    SerializableFunction serialize() const override;

private:
    DataType dataType;
    std::vector<LogicalFunction> parameters;
}};

}} // namespace NES
"""

LOGICAL_CPP_TEMPLATE = """\
/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#include <Functions/Meos/{nebula_name}LogicalFunction.hpp>

#include <DataTypes/DataType.hpp>
#include <DataTypes/DataTypeProvider.hpp>
#include <DataTypes/Schema.hpp>
#include <ErrorHandling.hpp>
#include <LogicalFunctionRegistry.hpp>
#include <Serialization/DataTypeSerializationUtil.hpp>
#include <fmt/format.h>
#include <SerializableVariantDescriptor.pb.h>

namespace NES
{{

{nebula_name}LogicalFunction::{nebula_name}LogicalFunction({ctor_logical_args})
    : dataType(DataTypeProvider::provideDataType(DataType::Type::{nautilus_return}))
{{
    parameters.reserve({n_args});
{ctor_logical_pushes}
}}

DataType {nebula_name}LogicalFunction::getDataType() const
{{
    return dataType;
}}

LogicalFunction {nebula_name}LogicalFunction::withDataType(const DataType& newDataType) const
{{
    auto copy = *this;
    copy.dataType = newDataType;
    return copy;
}}

std::vector<LogicalFunction> {nebula_name}LogicalFunction::getChildren() const
{{
    return parameters;
}}

LogicalFunction {nebula_name}LogicalFunction::withChildren(const std::vector<LogicalFunction>& children) const
{{
    PRECONDITION(children.size() == {n_args}, "{nebula_name}LogicalFunction requires {n_args} children, but got {{}}", children.size());
    auto copy = *this;
    copy.parameters = children;
    return copy;
}}

std::string_view {nebula_name}LogicalFunction::getType() const
{{
    return NAME;
}}

bool {nebula_name}LogicalFunction::operator==(const LogicalFunctionConcept& rhs) const
{{
    if (const auto* other = dynamic_cast<const {nebula_name}LogicalFunction*>(&rhs))
    {{
        return parameters == other->parameters;
    }}
    return false;
}}

std::string {nebula_name}LogicalFunction::explain(ExplainVerbosity verbosity) const
{{
    std::string args;
    for (size_t index = 0; index < parameters.size(); ++index)
    {{
        if (index > 0)
        {{
            args += ", ";
        }}
        args += parameters[index].explain(verbosity);
    }}
    return fmt::format("{{}}({{}})", NAME, args);
}}

LogicalFunction {nebula_name}LogicalFunction::withInferredDataType(const Schema& schema) const
{{
    std::vector<LogicalFunction> newChildren;
    newChildren.reserve(parameters.size());
    for (const auto& child : parameters)
    {{
        newChildren.emplace_back(child.withInferredDataType(schema));
    }}
    return withChildren(newChildren);
}}

SerializableFunction {nebula_name}LogicalFunction::serialize() const
{{
    SerializableFunction proto;
    proto.set_function_type(std::string(NAME));
    DataTypeSerializationUtil::serializeDataType(dataType, proto.mutable_data_type());
    for (const auto& child : parameters)
    {{
        proto.add_children()->CopyFrom(child.serialize());
    }}
    return proto;
}}

LogicalFunctionRegistryReturnType LogicalFunctionGeneratedRegistrar::Register{nebula_name}LogicalFunction(
    LogicalFunctionRegistryArguments arguments)
{{
    PRECONDITION(arguments.children.size() == {n_args},
                 "{nebula_name}LogicalFunction requires {n_args} children but got {{}}",
                 arguments.children.size());
{registrar_pushes}
}}

}} // namespace NES
"""

PHYSICAL_HPP_TEMPLATE = """\
/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Functions/PhysicalFunction.hpp>
#include <Nautilus/DataTypes/VarVal.hpp>
#include <Nautilus/Interface/Record.hpp>
#include <vector>

namespace NES {{

/**
 * @brief Physical operator for `{meos_call}`.
 *
 * {comment_one_liner}
 *
 * Generated by tools/codegen/codegen_nebula.py.
 */
class {nebula_name}PhysicalFunction : public PhysicalFunctionConcept {{
public:
    {nebula_name}PhysicalFunction({ctor_physical_args});

    VarVal execute(const Record& record, ArenaRef& arena) const override;

private:
    std::vector<PhysicalFunction> parameterFunctions;
}};

}} // namespace NES
"""

# Physical .cpp template; the `body` placeholder is the MEOS-call body
# (the heart of the operator). For `build_temporal_point` operators
# we emit a per-event temporal-point build + MEOS call, mirroring
# TemporalEDWithinGeometry; for non-temporal-point operators (future
# templates) the body shape differs and a separate template branch
# would be added here.
PHYSICAL_CPP_TEMPLATE_TEMPORAL_POINT = """\
/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#include <Functions/Meos/{nebula_name}PhysicalFunction.hpp>

#include <Functions/PhysicalFunction.hpp>
#include <MEOSWrapper.hpp>
#include <Nautilus/DataTypes/VarVal.hpp>
#include <Nautilus/DataTypes/VariableSizedData.hpp>
#include <Nautilus/Interface/Record.hpp>
#include <PhysicalFunctionRegistry.hpp>
#include <ErrorHandling.hpp>
#include <ExecutionContext.hpp>
#include <fmt/format.h>
#include <function.hpp>
#include <string>
#include <utility>
#include <val.hpp>

extern "C" {{
#include <meos.h>
#include <meos_geo.h>
}}

namespace NES {{

{nebula_name}PhysicalFunction::{nebula_name}PhysicalFunction({ctor_physical_args})
{{
    parameterFunctions.reserve({n_args});
{ctor_physical_pushes}
}}

VarVal {nebula_name}PhysicalFunction::execute(const Record& record, ArenaRef& arena) const
{{
    std::vector<VarVal> parameterValues;
    parameterValues.reserve(parameterFunctions.size());
    for (const auto& function : parameterFunctions)
    {{
        parameterValues.emplace_back(function.execute(record, arena));
    }}

    auto lon       = parameterValues[0].cast<nautilus::val<double>>();
    auto lat       = parameterValues[1].cast<nautilus::val<double>>();
    auto timestamp = parameterValues[2].cast<nautilus::val<uint64_t>>();
    auto geometry  = parameterValues[3].cast<VariableSizedData>();

    const auto result = nautilus::invoke(
        +[](double lonValue,
            double latValue,
            uint64_t timestampValue,
            const char* geometryPtr,
            uint32_t geometrySize) -> {return_type} {{
            try
            {{
                MEOS::Meos::ensureMeosInitialized();
                if (!(lonValue >= -180.0 && lonValue <= 180.0 && latValue >= -90.0 && latValue <= 90.0)) {{
                    return 0;
                }}

                const std::string timestampString = MEOS::Meos::convertEpochToTimestamp(timestampValue);
                std::string temporalGeometryWkt = fmt::format("SRID=4326;Point({{}} {{}})@{{}}", lonValue, latValue, timestampString);
                std::string staticGeometryWkt(geometryPtr, geometrySize);

                while (!staticGeometryWkt.empty() && (staticGeometryWkt.front() == '\\'' || staticGeometryWkt.front() == '"'))
                    staticGeometryWkt.erase(staticGeometryWkt.begin());
                while (!staticGeometryWkt.empty() && (staticGeometryWkt.back() == '\\'' || staticGeometryWkt.back() == '"'))
                    staticGeometryWkt.pop_back();

                if (temporalGeometryWkt.empty() || staticGeometryWkt.empty())
                    return 0;

                MEOS::Meos::TemporalGeometry temporalGeometry(temporalGeometryWkt);
                if (!temporalGeometry.getGeometry()) return 0;
                MEOS::Meos::StaticGeometry staticGeometry(staticGeometryWkt);
                if (!staticGeometry.getGeometry()) return 0;

                // MEOS spatial-relation call — same shape as TemporalEDWithin's
                // edwithin_tgeo_geo, but specific MEOS function per generated operator.
                // Real MEOS spatial-rel signature: int fn(const Temporal *, const GSERIALIZED *)
                // (no `atstart` flag — that's specific to geog_dwithin / edwithin's 3-arg variant).
                return {meos_call}(temporalGeometry.getGeometry(),
                                   staticGeometry.getGeometry());
            }}
            catch (const std::exception&)
            {{
                return 0;
            }}
        }},
        lon, lat, timestamp, geometry.getContent(), geometry.getContentSize());

    return VarVal(result);
}}

PhysicalFunctionRegistryReturnType PhysicalFunctionGeneratedRegistrar::Register{nebula_name}PhysicalFunction(
    PhysicalFunctionRegistryArguments arguments)
{{
    PRECONDITION(arguments.childFunctions.size() == {n_args},
                 "{nebula_name}PhysicalFunction requires {n_args} children but got {{}}",
                 arguments.childFunctions.size());
{registrar_pushes}
}}

}} // namespace NES
"""


def cpp_logical_type(arg):
    """C++ constructor-arg type for a LogicalFunction parameter."""
    return "LogicalFunction"


def cpp_physical_type(arg):
    """C++ constructor-arg type for a PhysicalFunction parameter."""
    return "PhysicalFunction"


def build_ctor_args(args, type_fn):
    return ",\n                                          ".join(
        f"{type_fn(a)} {a['name']}" for a in args
    )


def build_pushes_logical(args):
    return "\n".join(f"    parameters.push_back(std::move({a['name']}));" for a in args)


def build_pushes_physical(args):
    return "\n".join(
        f"    parameterFunctions.push_back(std::move({a['name']}Function));" for a in args
    )


def build_registrar_pushes_logical(args, nebula_name):
    pushes = []
    for i, _ in enumerate(args):
        pushes.append(f"    auto arg{i} = std::move(arguments.children[{i}]);")
    pushes.append(
        f"    return {nebula_name}LogicalFunction(" + ", ".join(f"std::move(arg{i})" for i in range(len(args))) + ");"
    )
    return "\n".join(pushes)


def build_registrar_pushes_physical(args, nebula_name):
    pushes = []
    for i, _ in enumerate(args):
        # PhysicalFunctionRegistryArguments uses `childFunctions`, not `children`
        # (LogicalFunctionRegistryArguments uses `children` — see registry headers).
        pushes.append(f"    auto arg{i} = std::move(arguments.childFunctions[{i}]);")
    pushes.append(
        f"    return {nebula_name}PhysicalFunction(" + ", ".join(f"std::move(arg{i})" for i in range(len(args))) + ");"
    )
    return "\n".join(pushes)


def emit_operator(op, output_root: Path):
    nebula_name = op["nebula_name"]
    n_args = len(op["args"])

    # Logical .hpp constructor args (LogicalFunction type each)
    ctor_logical_args = build_ctor_args(op["args"], cpp_logical_type)
    # Physical .hpp / .cpp constructor args use 'XxxFunction' naming convention
    physical_args = [{"name": a["name"] + "Function"} for a in op["args"]]
    ctor_physical_args = ",\n                                                          ".join(
        f"PhysicalFunction {a['name']}" for a in physical_args
    )

    ctor_logical_pushes = build_pushes_logical(op["args"])
    ctor_physical_pushes = build_pushes_physical(op["args"])
    registrar_l = build_registrar_pushes_logical(op["args"], nebula_name)
    registrar_p = build_registrar_pushes_physical(op["args"], nebula_name)

    common = {
        "nebula_name": nebula_name,
        "comment_one_liner": op["comment_one_liner"],
        "meos_call": op["meos_call"],
        "n_args": n_args,
        "nautilus_return": op["nautilus_return"],
        "return_type": op["return_type"],
        "ctor_logical_args": ctor_logical_args,
        "ctor_physical_args": ctor_physical_args,
        "ctor_logical_pushes": ctor_logical_pushes,
        "ctor_physical_pushes": ctor_physical_pushes,
        "registrar_pushes": registrar_l,
    }

    logical_hpp_path = output_root / "nes-logical-operators/include/Functions/Meos" / f"{nebula_name}LogicalFunction.hpp"
    logical_cpp_path = output_root / "nes-logical-operators/src/Functions/Meos" / f"{nebula_name}LogicalFunction.cpp"
    physical_hpp_path = output_root / "nes-physical-operators/include/Functions/Meos" / f"{nebula_name}PhysicalFunction.hpp"
    physical_cpp_path = output_root / "nes-physical-operators/src/Functions/Meos" / f"{nebula_name}PhysicalFunction.cpp"

    for p in (logical_hpp_path, logical_cpp_path, physical_hpp_path, physical_cpp_path):
        p.parent.mkdir(parents=True, exist_ok=True)

    logical_hpp_path.write_text(LOGICAL_HPP_TEMPLATE.format(**common))
    logical_cpp_path.write_text(LOGICAL_CPP_TEMPLATE.format(**common))
    physical_hpp_path.write_text(PHYSICAL_HPP_TEMPLATE.format(**common))

    physical_common = dict(common)
    physical_common["registrar_pushes"] = registrar_p
    if op.get("build_temporal_point"):
        physical_cpp_path.write_text(PHYSICAL_CPP_TEMPLATE_TEMPORAL_POINT.format(**physical_common))
    else:
        sys.stderr.write(
            f"  ! {nebula_name}: physical-cpp template for non-temporal-point ops is not yet implemented; "
            f"skipping .cpp — the .hpp + logical files are still emitted, but the .cpp must be hand-written.\n"
        )

    sys.stderr.write(f"  ✓ {nebula_name}: emitted 4 files ({logical_hpp_path.relative_to(output_root)} + siblings)\n")

    # Parser dispatch snippet (stderr — manual paste)
    sys.stderr.write(
        f"\n----- PASTE INTO nes-sql-parser/AntlrSQL.g4 (lexer tokens) -----\n"
        f"{op['sql_token']}: '{op['sql_token']}' | '{op['sql_token'].lower()}';\n"
    )
    sys.stderr.write(
        f"----- PASTE INTO nes-sql-parser/src/AntlrSQLQueryPlanCreator.cpp -----\n"
        f"        case AntlrSQLLexer::{op['sql_token']}:\n"
        f"            // Generated by tools/codegen/codegen_nebula.py. {op['comment_one_liner']}\n"
        f"            // 4-arg shape: lon, lat, timestamp, geometry — mirrors TemporalEDWithinGeometry.\n"
        f"            {{\n"
        f"                // Arg-extraction + construct{n_args}-children pattern mirrors the existing\n"
        f"                // TEMPORAL_EDWITHIN_GEOMETRY block in this file. Adopt the same\n"
        f"                // constantBuilder / functionBuilder pop + tryGet<FieldAccessLogicalFunction>\n"
        f"                // gating.\n"
        f"            }}\n"
        f"            break;\n"
        f"----- end snippet -----\n\n"
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="Path to JSON descriptor file")
    parser.add_argument("--output-root", required=True, help="MobilityNebula repo root")
    args = parser.parse_args()

    with open(args.input) as f:
        config = json.load(f)

    output_root = Path(args.output_root).resolve()
    if not (output_root / "nes-logical-operators").exists():
        sys.exit(f"ERROR: {output_root} does not look like a MobilityNebula root (no nes-logical-operators/)")

    operators = config["operators"]
    sys.stderr.write(f"Emitting {len(operators)} operator(s):\n\n")
    for op in operators:
        emit_operator(op, output_root)

    sys.stderr.write(
        f"\nDone. {len(operators) * 4} files emitted (or 3 + .cpp-skipped for non-temporal-point ops).\n"
        f"Manual steps after running this script:\n"
        f"  1. Paste the AntlrSQL.g4 lexer-token snippets (above) into the .g4 file\n"
        f"  2. Paste the AntlrSQLQueryPlanCreator.cpp dispatch snippets into the parser\n"
        f"  3. Add the new .cpp files to nes-logical-operators/src/Functions/Meos/CMakeLists.txt\n"
        f"     and nes-physical-operators/src/Functions/Meos/CMakeLists.txt\n"
        f"  4. Run `cmake --build` to compile-verify; expect to iterate on the templates\n"
        f"     for any first-batch compile errors\n"
    )


if __name__ == "__main__":
    main()
