/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

grammar AntlrSQL;

@lexer::postinclude {
#include <Util/DisableWarningsPragma.hpp>
DISABLE_WARNING_PUSH
DISABLE_WARNING(-Wlogical-op-parentheses)
DISABLE_WARNING(-Wunused-parameter)
}

@parser::postinclude {
#include <Util/DisableWarningsPragma.hpp>
DISABLE_WARNING_PUSH
DISABLE_WARNING(-Wlogical-op-parentheses)
DISABLE_WARNING(-Wunused-parameter)
}

@parser::members {
      bool SQL_standard_keyword_behavior = false;
      bool legacy_exponent_literal_as_decimal_enabled = false;
}

@lexer::members {
  bool isValidDecimal() {
    int nextChar = _input->LA(1);
    if (nextChar >= 'A' && nextChar <= 'Z' || nextChar >= '0' && nextChar <= '9' ||
      nextChar == '_') {
      return false;
    } else {
      return true;
    }
  }

  bool isHint() {
    int nextChar = _input->LA(1);
    if (nextChar == '+') {
      return true;
    } else {
      return false;
    }
  }
}

singleStatement: statement ';'? EOF;

terminatedStatement: statement ';';
multipleStatements: (statement (';' statement)* ';'?)? EOF;
statement: query | createStatement | dropStatement | showStatement;

createStatement: CREATE createDefinition;
createDefinition: createLogicalSourceDefinition | createPhysicalSourceDefinition | createSinkDefinition;
createLogicalSourceDefinition: LOGICAL SOURCE sourceName=identifier schemaDefinition fromQuery?;

createPhysicalSourceDefinition: PHYSICAL SOURCE FOR logicalSource=identifier
                                TYPE type=identifier
                                (SET '(' options=namedConfigExpressionSeq ')')?;

createSinkDefinition: SINK sinkName=identifier schemaDefinition TYPE type=identifier (SET '(' options=namedConfigExpressionSeq ')')?;


schemaDefinition: '(' columnDefinition (',' columnDefinition)* ')';
columnDefinition: identifierChain typeDefinition;

typeDefinition: DATA_TYPE;

fromQuery: AS query;

dropStatement: DROP dropSubject;
dropSubject: dropQuery | dropSource | dropSink;
dropQuery: QUERY id=unsignedIntegerLiteral;
dropSource: dropLogicalSourceSubject | dropPhysicalSourceSubject;
dropLogicalSourceSubject: LOGICAL SOURCE name=strictIdentifier;
dropPhysicalSourceSubject: PHYSICAL SOURCE id=unsignedIntegerLiteral;
dropSink: SINK name=strictIdentifier;

showStatement: SHOW showSubject (WHERE showFilter)? (FORMAT showFormat)?;
showFormat: TEXT | JSON;
showSubject: QUERIES #showQueriesSubject
    | LOGICAL SOURCES #showLogicalSourcesSubject
    | PHYSICAL SOURCES (FOR logicalSourceName=strictIdentifier)? #showPhysicalSourcesSubject
    | SINKS #showSinksSubject;

showFilter: attr=strictIdentifier EQ value=constant;

query : queryTerm queryOrganization;

queryOrganization:
         (ORDER BY order+=sortItem (',' order+=sortItem)*)?
         (LIMIT (ALL | limit=INTEGER_VALUE))?
         (OFFSET offset=INTEGER_VALUE)?
         ;

queryTerm: queryPrimary #primaryQuery
         |  left=queryTerm setoperator=UNION right=queryTerm  #setOperation
         ;

queryPrimary
    : querySpecification                                                    #queryPrimaryDefault
    | fromStatement                                                         #fromStmt
    | TABLE multipartIdentifier                                             #table
    | inlineTable                                                           #inlineTableDefault1
    | '(' query ')'                                                         #subquery
    ;
/// new layout to be closer to traditional SQL
querySpecification: selectClause fromClause whereClause? windowedAggregationClause? havingClause? sinkClause?;


fromClause: FROM relation (',' relation)*;

relation
    : relationPrimary joinRelation*
    ;

joinRelation
    : (joinType) JOIN right=relationPrimary joinCriteria? windowClause
    | NATURAL joinType JOIN right=relationPrimary windowClause
    ;

joinType
    : INNER?
    ;

joinCriteria
    : ON booleanExpression
    ;

relationPrimary
    : multipartIdentifier tableAlias          #tableName
    | '(' query ')'  tableAlias               #aliasedQuery
    | '(' relation ')' tableAlias             #aliasedRelation
    | inlineTable                             #inlineTableDefault2
    | inlineSource                            #inlineDefinedSource
    ;

inlineSource
    : type=identifier '(' parameters=namedConfigExpressionSeq ')'
    ;

schema: SCHEMA schemaDefinition
 ;

fromStatement: fromClause fromStatementBody+;

fromStatementBody: selectClause whereClause? groupByClause?;

selectClause : SELECT (hints+=hint)* namedExpressionSeq;

whereClause: WHERE booleanExpression;

havingClause: HAVING booleanExpression;

inlineTable
    : VALUES expression (',' expression)* tableAlias
    ;

tableAlias
    : (AS? identifier identifierList?)?
    ;

multipartIdentifier
    : parts+=errorCapturingIdentifier ('.' parts+=errorCapturingIdentifier)*
    ;

namedConfigExpression: (constant | schema) AS name=identifierChain;

namedExpression
    : expression AS name=identifier
    | expression
    ;

identifier: strictIdentifier;

strictIdentifier
    : IDENTIFIER #unquotedIdentifier
    | quotedIdentifier #quotedIdentifierAlternative;

quotedIdentifier
    : BACKQUOTED_IDENTIFIER
    ;

BACKQUOTED_IDENTIFIER
    : '`' ( ~'`' | '``' )* '`'
    ;

identifierChain: strictIdentifier ('.' strictIdentifier)*;

identifierList
    : '(' identifierSeq ')'
    ;

identifierSeq
    : ident+=errorCapturingIdentifier (',' ident+=errorCapturingIdentifier)*
    ;

errorCapturingIdentifier
    : identifier errorCapturingIdentifierExtra
    ;

errorCapturingIdentifierExtra
    : (MINUS identifier)+    #errorIdent
    |                        #realIdent
    ;

namedConfigExpressionSeq: (namedConfigExpression (',' namedConfigExpression)*)?;
namedExpressionSeq
    : namedExpression (',' namedExpression)*
    ;

expression
    : valueExpression
    | booleanExpression
    | identifier
    | schema
    ;

booleanExpression
    : NOT booleanExpression                                        #logicalNot
    | EXISTS '(' query ')'                                         #exists
    | valueExpression predicate?                                   #predicated
    | left=booleanExpression op=AND right=booleanExpression  #logicalBinary
    | left=booleanExpression op=OR right=booleanExpression   #logicalBinary
    ;

/// Problem fixed that the querySpecification rule could match an empty string
windowedAggregationClause:
    groupByClause? windowClause watermarkClause?
    | windowClause groupByClause? watermarkClause?;

groupByClause
    : GROUP BY groupingExpressions+=expression (',' groupingExpressions+=expression)* (
      WITH kind=ROLLUP
    | WITH kind=CUBE
    | kind=GROUPING SETS '(' groupingSet (',' groupingSet)* ')')?
    | GROUP BY kind=GROUPING SETS '(' groupingSet (',' groupingSet)* ')'
    ;

groupingSet
    : '(' (expression (',' expression)*)? ')'
    | expression
    ;

windowClause
    : WINDOW windowSpec
    ;

watermarkClause: WATERMARK '(' watermarkParameters ')';

watermarkParameters: watermarkIdentifier=identifier ',' watermark=INTEGER_VALUE watermarkTimeUnit=timeUnit;
/// Adding Threshold Windows
windowSpec:
    timeWindow #timeBasedWindow
    | countWindow #countBasedWindow
    | conditionWindow #thresholdBasedWindow
    ;

timeWindow
    : TUMBLING '(' (timestampParameter ',')?  sizeParameter ')'                       #tumblingWindow
    | SLIDING '(' (timestampParameter ',')? sizeParameter ',' advancebyParameter ')' #slidingWindow
    ;

countWindow:
    TUMBLING '(' INTEGER_VALUE ')'    #countBasedTumbling
    ;

conditionWindow
    : THRESHOLD '(' conditionParameter (',' thresholdMinSizeParameter)? ')' #thresholdWindow
    ;

conditionParameter: expression;
thresholdMinSizeParameter: INTEGER_VALUE;

sizeParameter: SIZE INTEGER_VALUE timeUnit;

advancebyParameter: ADVANCE BY INTEGER_VALUE timeUnit;

timeUnit: MS
        | SEC
        | MINUTE
        | HOUR
        | DAY
        ;

timestampParameter: name=identifier;

functionName:  IDENTIFIER | AVG | MAX | MIN | SUM | COUNT | MEDIAN | ARRAY_AGG | VAR | TEMPORAL_SEQUENCE | TEMPORAL_LENGTH | PAIR_MEETING | CROSS_DISTANCE | TEMPORAL_EINTERSECTS_GEOMETRY | TEMPORAL_AINTERSECTS_GEOMETRY | TEMPORAL_ECONTAINS_GEOMETRY | EDWITHIN_TGEO_GEO | TGEO_AT_STBOX | TEMPORAL_ADISJOINT_GEOMETRY | TEMPORAL_ECONTAINS_TGEOMETRY | TEMPORAL_ECOVERS_TGEOMETRY | TEMPORAL_EDISJOINT_TGEOMETRY | TEMPORAL_EINTERSECTS_TGEOMETRY | TEMPORAL_ETOUCHES_TGEOMETRY | TEMPORAL_ACONTAINS_TGEOMETRY | TEMPORAL_ADISJOINT_TGEOMETRY | TEMPORAL_AINTERSECTS_TGEOMETRY | TEMPORAL_ATOUCHES_TGEOMETRY | TEMPORAL_NAD_GEOMETRY | TEMPORAL_NAD_TGEOMETRY | TEMPORAL_EDWITHIN_TGEOMETRY | TEMPORAL_ADWITHIN_GEOMETRY | TEMPORAL_ADWITHIN_TGEOMETRY | TEMPORAL_EDISJOINT_GEOMETRY | TEMPORAL_ATOUCHES_GEOMETRY | TEMPORAL_ECOVERS_GEOMETRY | TEMPORAL_ACONTAINS_GEOMETRY | TEMPORAL_ETOUCHES_GEOMETRY | TEMPORAL_NAD_FLOAT_SCALAR | TEMPORAL_NAD_INT_SCALAR | TEMPORAL_NAD_TFLOAT | TEMPORAL_NAD_TINT | TEMPORAL_AT_GEOMETRY | TEMPORAL_MINUS_GEOMETRY | TEMPORAL_NUM_INSTANTS | TEMPORAL_NUM_SEQUENCES | TEMPORAL_NUM_TIMESTAMPS | TEMPORAL_TFLOAT_START_VALUE | TEMPORAL_TFLOAT_END_VALUE | TEMPORAL_TFLOAT_MIN_VALUE | TEMPORAL_TFLOAT_MAX_VALUE | TEMPORAL_TNUMBER_INTEGRAL | TEMPORAL_TINT_START_VALUE | TEMPORAL_TINT_END_VALUE | TEMPORAL_TINT_MIN_VALUE | TEMPORAL_TINT_MAX_VALUE | TEMPORAL_TFLOAT_AVG_VALUE | TEMPORAL_TNUMBER_TWAVG | TEMPORAL_TINT_AVG_VALUE | TEMPORAL_START_TIMESTAMP | TEMPORAL_END_TIMESTAMP | TEMPORAL_LOWER_INC | TEMPORAL_UPPER_INC | TEMPORAL_TPOINT_IS_SIMPLE | TEMPORAL_ECONTAINS_TCBUFFER | TEMPORAL_ECOVERS_TCBUFFER | TEMPORAL_EDISJOINT_TCBUFFER | TEMPORAL_EINTERSECTS_TCBUFFER | TEMPORAL_ETOUCHES_TCBUFFER | TEMPORAL_ACONTAINS_TCBUFFER | TEMPORAL_ACOVERS_TCBUFFER | TEMPORAL_ADISJOINT_TCBUFFER | TEMPORAL_AINTERSECTS_TCBUFFER | TEMPORAL_ATOUCHES_TCBUFFER | TEMPORAL_ECONTAINS_TCBUFFER_CBUFFER | TEMPORAL_ECOVERS_TCBUFFER_CBUFFER | TEMPORAL_EDISJOINT_TCBUFFER_CBUFFER | TEMPORAL_EINTERSECTS_TCBUFFER_CBUFFER | TEMPORAL_ETOUCHES_TCBUFFER_CBUFFER | TEMPORAL_ACONTAINS_TCBUFFER_CBUFFER | TEMPORAL_ACOVERS_TCBUFFER_CBUFFER | TEMPORAL_ADISJOINT_TCBUFFER_CBUFFER | TEMPORAL_AINTERSECTS_TCBUFFER_CBUFFER | TEMPORAL_ATOUCHES_TCBUFFER_CBUFFER | TEMPORAL_ADISJOINT_TCBUFFER_TCBUFFER | TEMPORAL_AINTERSECTS_TCBUFFER_TCBUFFER | TEMPORAL_ATOUCHES_TCBUFFER_TCBUFFER | TEMPORAL_ECOVERS_TCBUFFER_TCBUFFER | TEMPORAL_EINTERSECTS_TCBUFFER_TCBUFFER | TEMPORAL_ETOUCHES_TCBUFFER_TCBUFFER | TEMPORAL_EDWITHIN_TCBUFFER_GEOMETRY | TEMPORAL_ADWITHIN_TCBUFFER_GEOMETRY | TEMPORAL_EDWITHIN_TCBUFFER_CBUFFER | TEMPORAL_ADWITHIN_TCBUFFER_CBUFFER | TEMPORAL_EDWITHIN_TCBUFFER_TCBUFFER | TEMPORAL_ADWITHIN_TCBUFFER_TCBUFFER | TEMPORAL_ECONTAINS_TPOSE_GEOMETRY | TEMPORAL_ECOVERS_TPOSE_GEOMETRY | TEMPORAL_EDISJOINT_TPOSE_GEOMETRY | TEMPORAL_EINTERSECTS_TPOSE_GEOMETRY | TEMPORAL_ETOUCHES_TPOSE_GEOMETRY | TEMPORAL_ACONTAINS_TPOSE_GEOMETRY | TEMPORAL_ADISJOINT_TPOSE_GEOMETRY | TEMPORAL_AINTERSECTS_TPOSE_GEOMETRY | TEMPORAL_ATOUCHES_TPOSE_GEOMETRY | TEMPORAL_ECONTAINS_TPOSE_TPOSE | TEMPORAL_ECOVERS_TPOSE_TPOSE | TEMPORAL_EDISJOINT_TPOSE_TPOSE | TEMPORAL_EINTERSECTS_TPOSE_TPOSE | TEMPORAL_ETOUCHES_TPOSE_TPOSE | TEMPORAL_ACONTAINS_TPOSE_TPOSE | TEMPORAL_ADISJOINT_TPOSE_TPOSE | TEMPORAL_AINTERSECTS_TPOSE_TPOSE | TEMPORAL_ATOUCHES_TPOSE_TPOSE | TEMPORAL_ECONTAINS_TNPOINT_GEOMETRY | TEMPORAL_ECONTAINS_TNPOINT_TNPOINT | TEMPORAL_ECOVERS_TNPOINT_GEOMETRY | TEMPORAL_ECOVERS_TNPOINT_TNPOINT | TEMPORAL_EDISJOINT_TNPOINT_GEOMETRY | TEMPORAL_EDISJOINT_TNPOINT_TNPOINT | TEMPORAL_EINTERSECTS_TNPOINT_GEOMETRY | TEMPORAL_EINTERSECTS_TNPOINT_TNPOINT | TEMPORAL_ETOUCHES_TNPOINT_GEOMETRY | TEMPORAL_ETOUCHES_TNPOINT_TNPOINT | TEMPORAL_ACONTAINS_TNPOINT_GEOMETRY | TEMPORAL_ACONTAINS_TNPOINT_TNPOINT | TEMPORAL_ADISJOINT_TNPOINT_GEOMETRY | TEMPORAL_ADISJOINT_TNPOINT_TNPOINT | TEMPORAL_AINTERSECTS_TNPOINT_GEOMETRY | TEMPORAL_AINTERSECTS_TNPOINT_TNPOINT | TEMPORAL_ATOUCHES_TNPOINT_GEOMETRY | TEMPORAL_ATOUCHES_TNPOINT_TNPOINT | TEMPORAL_NAD_TPOSE_GEOMETRY | TEMPORAL_NAD_TPOSE_TPOSE | TEMPORAL_NAD_TNPOINT_GEOMETRY | TEMPORAL_NAD_TNPOINT_TNPOINT | TEMPORAL_EDWITHIN_TPOSE_GEOMETRY | TEMPORAL_EDWITHIN_TPOSE_TPOSE | TEMPORAL_EDWITHIN_TNPOINT_GEOMETRY | TEMPORAL_EDWITHIN_TNPOINT_TNPOINT | TEMPORAL_ADWITHIN_TPOSE_GEOMETRY | TEMPORAL_ADWITHIN_TPOSE_TPOSE | TEMPORAL_ADWITHIN_TNPOINT_GEOMETRY | TEMPORAL_ADWITHIN_TNPOINT_TNPOINT | TEMPORAL_NAD_TCBUFFER | TEMPORAL_NAD_TCBUFFER_CBUFFER | TEMPORAL_NAD_TCBUFFER_TCBUFFER | ALWAYS_EQ_TFLOAT_FLOAT | ALWAYS_EQ_TINT_INT | ALWAYS_GE_TFLOAT_FLOAT | ALWAYS_GE_TINT_INT | ALWAYS_GT_TFLOAT_FLOAT | ALWAYS_GT_TINT_INT | ALWAYS_LE_TFLOAT_FLOAT | ALWAYS_LE_TINT_INT | ALWAYS_LT_TFLOAT_FLOAT | ALWAYS_LT_TINT_INT | ALWAYS_NE_TFLOAT_FLOAT | ALWAYS_NE_TINT_INT | EVER_EQ_TFLOAT_FLOAT | EVER_EQ_TINT_INT | EVER_GE_TFLOAT_FLOAT | EVER_GE_TINT_INT | EVER_GT_TFLOAT_FLOAT | EVER_GT_TINT_INT | EVER_LE_TFLOAT_FLOAT | EVER_LE_TINT_INT | EVER_LT_TFLOAT_FLOAT | EVER_LT_TINT_INT | EVER_NE_TFLOAT_FLOAT | EVER_NE_TINT_INT | ALWAYS_EQ_FLOAT_TFLOAT | ALWAYS_EQ_INT_TINT | ALWAYS_EQ_TEMPORAL_TEMPORAL | ALWAYS_GE_FLOAT_TFLOAT | ALWAYS_GE_INT_TINT | ALWAYS_GE_TEMPORAL_TEMPORAL | ALWAYS_GT_FLOAT_TFLOAT | ALWAYS_GT_INT_TINT | ALWAYS_GT_TEMPORAL_TEMPORAL | ALWAYS_LE_FLOAT_TFLOAT | ALWAYS_LE_INT_TINT | ALWAYS_LE_TEMPORAL_TEMPORAL | ALWAYS_LT_FLOAT_TFLOAT | ALWAYS_LT_INT_TINT | ALWAYS_LT_TEMPORAL_TEMPORAL | ALWAYS_NE_FLOAT_TFLOAT | ALWAYS_NE_INT_TINT | ALWAYS_NE_TEMPORAL_TEMPORAL | EVER_EQ_FLOAT_TFLOAT | EVER_EQ_INT_TINT | EVER_EQ_TEMPORAL_TEMPORAL | EVER_GE_FLOAT_TFLOAT | EVER_GE_INT_TINT | EVER_GE_TEMPORAL_TEMPORAL | EVER_GT_FLOAT_TFLOAT | EVER_GT_INT_TINT | EVER_GT_TEMPORAL_TEMPORAL | EVER_LE_FLOAT_TFLOAT | EVER_LE_INT_TINT | EVER_LE_TEMPORAL_TEMPORAL | EVER_LT_FLOAT_TFLOAT | EVER_LT_INT_TINT | EVER_LT_TEMPORAL_TEMPORAL | EVER_NE_FLOAT_TFLOAT | EVER_NE_INT_TINT | EVER_NE_TEMPORAL_TEMPORAL | ALWAYS_EQ_TCBUFFER_CBUFFER | ALWAYS_EQ_TCBUFFER_TCBUFFER | ALWAYS_EQ_TGEO_GEO | ALWAYS_EQ_TGEO_TGEO | ALWAYS_NE_TCBUFFER_CBUFFER | ALWAYS_NE_TCBUFFER_TCBUFFER | ALWAYS_NE_TGEO_GEO | ALWAYS_NE_TGEO_TGEO | ATOUCHES_TPOINT_GEO | ETOUCHES_TPOINT_GEO | EVER_EQ_TCBUFFER_CBUFFER | EVER_EQ_TCBUFFER_TCBUFFER | EVER_EQ_TGEO_GEO | EVER_EQ_TGEO_TGEO | EVER_NE_TCBUFFER_CBUFFER | EVER_NE_TCBUFFER_TCBUFFER | EVER_NE_TGEO_GEO | EVER_NE_TGEO_TGEO | ABOVE_TSPATIAL_TSPATIAL | ADJACENT_TEMPORAL_TEMPORAL | ADJACENT_TSPATIAL_TSPATIAL | AFTER_TEMPORAL_TEMPORAL | AFTER_TSPATIAL_TSPATIAL | ALWAYS_EQ_TBOOL_BOOL | ALWAYS_NE_TBOOL_BOOL | BACK_TSPATIAL_TSPATIAL | BEFORE_TEMPORAL_TEMPORAL | BEFORE_TSPATIAL_TSPATIAL | BELOW_TSPATIAL_TSPATIAL | CONTAINED_TEMPORAL_TEMPORAL | CONTAINED_TSPATIAL_TSPATIAL | CONTAINS_TEMPORAL_TEMPORAL | CONTAINS_TSPATIAL_TSPATIAL | EVER_EQ_TBOOL_BOOL | EVER_NE_TBOOL_BOOL | FRONT_TSPATIAL_TSPATIAL | LEFT_TSPATIAL_TSPATIAL | NAD_TNPOINT_GEO | NAD_TPOSE_GEO | OVERABOVE_TSPATIAL_TSPATIAL | OVERAFTER_TEMPORAL_TEMPORAL | OVERAFTER_TSPATIAL_TSPATIAL | OVERBACK_TSPATIAL_TSPATIAL | OVERBEFORE_TEMPORAL_TEMPORAL | OVERBEFORE_TSPATIAL_TSPATIAL | OVERBELOW_TSPATIAL_TSPATIAL | OVERFRONT_TSPATIAL_TSPATIAL | OVERLAPS_TEMPORAL_TEMPORAL | OVERLAPS_TSPATIAL_TSPATIAL | OVERLEFT_TSPATIAL_TSPATIAL | OVERRIGHT_TSPATIAL_TSPATIAL | RIGHT_TSPATIAL_TSPATIAL | SAME_TEMPORAL_TEMPORAL | SAME_TSPATIAL_TSPATIAL | TBOOL_END_VALUE | TBOOL_START_VALUE | TEMPORAL_CMP | TEMPORAL_DYNTIMEWARP_DISTANCE | TEMPORAL_EQ | TEMPORAL_FRECHET_DISTANCE | TEMPORAL_GE | TEMPORAL_GT | TEMPORAL_HAUSDORFF_DISTANCE | TEMPORAL_LE | TEMPORAL_LT | TEMPORAL_NE | TNPOINT_LENGTH | TBOOL_TO_TINT | TCBUFFER_TO_TFLOAT | TFLOAT_CEIL | TFLOAT_EXP | TFLOAT_FLOOR | TFLOAT_LN | TFLOAT_LOG10 | TFLOAT_RADIANS | TFLOAT_TO_TINT | TINT_TO_TFLOAT | ADJACENT_TNUMBER_TBOX | AFTER_TNUMBER_TBOX | BEFORE_TNUMBER_TBOX | CONTAINED_TNUMBER_TBOX | CONTAINS_TNUMBER_TBOX | LEFT_TNUMBER_TBOX | NAD_TCBUFFER_STBOX | NAD_TFLOAT_TBOX | NAD_TGEO_STBOX | NAD_TINT_TBOX | NAD_TNPOINT_STBOX | NAD_TPOSE_STBOX | OVERAFTER_TNUMBER_TBOX | OVERBEFORE_TNUMBER_TBOX | OVERLAPS_TNUMBER_TBOX | OVERLEFT_TNUMBER_TBOX | OVERRIGHT_TNUMBER_TBOX | RIGHT_TNUMBER_TBOX | SAME_TNUMBER_TBOX | TSPATIAL_EXTENT | TNUMBER_EXTENT | FLOAT_EXTENT | INT_EXTENT | BIGINT_EXTENT | TIMESTAMPTZ_EXTENT | ABOVE_STBOX_TSPATIAL | ABOVE_TSPATIAL_STBOX | ADJACENT_STBOX_TSPATIAL | ADJACENT_TBOX_TNUMBER | ADJACENT_TSPATIAL_STBOX | AFTER_STBOX_TSPATIAL | AFTER_TBOX_TNUMBER | AFTER_TSPATIAL_STBOX | BACK_STBOX_TSPATIAL | BACK_TSPATIAL_STBOX | BEFORE_STBOX_TSPATIAL | BEFORE_TBOX_TNUMBER | BEFORE_TSPATIAL_STBOX | BELOW_STBOX_TSPATIAL | BELOW_TSPATIAL_STBOX | CONTAINED_STBOX_TSPATIAL | CONTAINED_TBOX_TNUMBER | CONTAINED_TSPATIAL_STBOX | CONTAINS_STBOX_TSPATIAL | CONTAINS_TBOX_TNUMBER | CONTAINS_TSPATIAL_STBOX | FRONT_STBOX_TSPATIAL | FRONT_TSPATIAL_STBOX | LEFT_STBOX_TSPATIAL | LEFT_TBOX_TNUMBER | LEFT_TSPATIAL_STBOX | OVERABOVE_STBOX_TSPATIAL | OVERABOVE_TSPATIAL_STBOX | OVERAFTER_STBOX_TSPATIAL | OVERAFTER_TBOX_TNUMBER | OVERAFTER_TSPATIAL_STBOX | OVERBACK_STBOX_TSPATIAL | OVERBACK_TSPATIAL_STBOX | OVERBEFORE_STBOX_TSPATIAL | OVERBEFORE_TBOX_TNUMBER | OVERBEFORE_TSPATIAL_STBOX | OVERBELOW_STBOX_TSPATIAL | OVERBELOW_TSPATIAL_STBOX | OVERFRONT_STBOX_TSPATIAL | OVERFRONT_TSPATIAL_STBOX | OVERLAPS_STBOX_TSPATIAL | OVERLAPS_TBOX_TNUMBER | OVERLAPS_TSPATIAL_STBOX | OVERLEFT_STBOX_TSPATIAL | OVERLEFT_TBOX_TNUMBER | OVERLEFT_TSPATIAL_STBOX | OVERRIGHT_STBOX_TSPATIAL | OVERRIGHT_TBOX_TNUMBER | OVERRIGHT_TSPATIAL_STBOX | RIGHT_STBOX_TSPATIAL | RIGHT_TBOX_TNUMBER | RIGHT_TSPATIAL_STBOX | SAME_STBOX_TSPATIAL | SAME_TBOX_TNUMBER | SAME_TSPATIAL_STBOX | FLOAT_UNION | INT_UNION | BIGINT_UNION | TIMESTAMPTZ_UNION | TPOINT_LENGTH_WKB | TRAJECTORY_WKB | TLENGTH_EXP | TGEO_CENTROID_EXP | TPOINT_AZIMUTH_EXP | TPOINT_ANGULAR_DIFFERENCE_EXP | TGEOMPOINT_TO_TGEOMETRY_EXP | TEMPORAL_COPY_EXP | TNUMBER_ABS_EXP | TNUMBER_DELTA_VALUE_EXP | TNUMBER_ANGULAR_DIFFERENCE_EXP | TEMPORAL_DERIVATIVE_EXP | TEMPORAL_AT_MAX_EXP | TEMPORAL_AT_MIN_EXP | TEMPORAL_MINUS_MAX_EXP | TEMPORAL_MINUS_MIN_EXP | TNPOINT_CUMULATIVE_LENGTH_EXP | TNPOINT_SPEED_EXP | TNPOINT_TO_TGEOMPOINT_EXP | TPOINT_CUMULATIVE_LENGTH_EXP | TPOINT_SPEED_EXP | TPOINT_GET_X_EXP | TPOINT_GET_Y_EXP | TNUMBER_TREND_EXP | TGEO_START_VALUE_EXP | TGEO_END_VALUE_EXP | TGEO_CONVEX_HULL_EXP | TPOINT_TWCENTROID_EXP | ABOVE_STBOX_STBOX | ADJACENT_STBOX_STBOX | AFTER_STBOX_STBOX | BACK_STBOX_STBOX | BEFORE_STBOX_STBOX | BELOW_STBOX_STBOX | CONTAINED_STBOX_STBOX | CONTAINS_STBOX_STBOX | FRONT_STBOX_STBOX | LEFT_STBOX_STBOX | NAD_STBOX_STBOX | OVERABOVE_STBOX_STBOX | OVERAFTER_STBOX_STBOX | OVERBACK_STBOX_STBOX | OVERBEFORE_STBOX_STBOX | OVERBELOW_STBOX_STBOX | OVERFRONT_STBOX_STBOX | OVERLAPS_STBOX_STBOX | OVERLEFT_STBOX_STBOX | OVERRIGHT_STBOX_STBOX | RIGHT_STBOX_STBOX | SAME_STBOX_STBOX | STBOX_CMP | STBOX_EQ | STBOX_GE | STBOX_GT | STBOX_LE | STBOX_LT | STBOX_NE | ADJACENT_TNUMBER_TNUMBER | AFTER_TNUMBER_TNUMBER | BEFORE_TNUMBER_TNUMBER | CONTAINED_TNUMBER_TNUMBER | CONTAINS_TNUMBER_TNUMBER | LEFT_TNUMBER_TNUMBER | OVERAFTER_TNUMBER_TNUMBER | OVERBEFORE_TNUMBER_TNUMBER | OVERLAPS_TNUMBER_TNUMBER | OVERLEFT_TNUMBER_TNUMBER | OVERRIGHT_TNUMBER_TNUMBER | RIGHT_TNUMBER_TNUMBER | SAME_TNUMBER_TNUMBER | ALWAYS_EQ_TNPOINT_TNPOINT | ALWAYS_EQ_TPOSE_TPOSE | ALWAYS_NE_TNPOINT_TNPOINT | ALWAYS_NE_TPOSE_TPOSE | EVER_EQ_TNPOINT_TNPOINT | EVER_EQ_TPOSE_TPOSE | EVER_NE_TNPOINT_TNPOINT | EVER_NE_TPOSE_TPOSE | NAD_TNPOINT_TNPOINT | NAD_TPOSE_TPOSE | ADD_TNUMBER_TNUMBER | DIV_TNUMBER_TNUMBER | MUL_TNUMBER_TNUMBER | SUB_TNUMBER_TNUMBER | TCONTAINS_TCBUFFER_TCBUFFER | TCONTAINS_TGEO_TGEO | TCOVERS_TCBUFFER_TCBUFFER | TCOVERS_TGEO_TGEO | TDISTANCE_TCBUFFER_TCBUFFER | TDISTANCE_TGEO_TGEO | TDISTANCE_TNPOINT_TNPOINT | TDISTANCE_TNUMBER_TNUMBER | TDISTANCE_TPOSE_TPOSE | CONTAINS_SPAN_SPAN | CONTAINED_SPAN_SPAN | ADJACENT_SPAN_SPAN | LEFT_SPAN_SPAN | RIGHT_SPAN_SPAN | OVERLAPS_SPAN_SPAN | OVERLEFT_SPAN_SPAN | OVERRIGHT_SPAN_SPAN | CONTAINS_SET_SET | CONTAINED_SET_SET | LEFT_SET_SET | RIGHT_SET_SET | OVERLAPS_SET_SET | OVERLEFT_SET_SET | OVERRIGHT_SET_SET | CONTAINS_SPANSET_SPAN | CONTAINED_SPANSET_SPAN | ADJACENT_SPANSET_SPAN | LEFT_SPANSET_SPAN | RIGHT_SPANSET_SPAN | OVERLAPS_SPANSET_SPAN | OVERLEFT_SPANSET_SPAN | OVERRIGHT_SPANSET_SPAN | CONTAINS_SPANSET_SPANSET | CONTAINED_SPANSET_SPANSET | ADJACENT_SPANSET_SPANSET | LEFT_SPANSET_SPANSET | RIGHT_SPANSET_SPANSET | OVERLAPS_SPANSET_SPANSET | OVERLEFT_SPANSET_SPANSET | OVERRIGHT_SPANSET_SPANSET | UNION_SPAN_SPAN | INTERSECTION_SPAN_SPAN | MINUS_SPAN_SPAN | UNION_SET_SET | INTERSECTION_SET_SET | MINUS_SET_SET | UNION_SPANSET_SPANSET | INTERSECTION_SPANSET_SPANSET | MINUS_SPANSET_SPANSET | UNION_SPAN_SPANSET | INTERSECTION_SPAN_SPANSET | MINUS_SPAN_SPANSET | UNION_SPANSET_SPAN | INTERSECTION_SPANSET_SPAN | MINUS_SPANSET_SPAN | ADJACENT_SPAN_FLOAT | ADJACENT_SPAN_INT | ADJACENT_SPANSET_BIGINT | ADJACENT_SPANSET_FLOAT | ADJACENT_SPANSET_INT | BEFORE_TBOX_TBOX | CONTAINED_BIGINT_SET | CONTAINED_BIGINT_SPAN | CONTAINED_BIGINT_SPANSET | CONTAINED_FLOAT_SET | CONTAINED_FLOAT_SPAN | CONTAINED_FLOAT_SPANSET | CONTAINED_INT_SET | CONTAINED_INT_SPAN | CONTAINED_INT_SPANSET | CONTAINED_TBOX_TBOX | CONTAINS_SET_BIGINT | CONTAINS_SET_FLOAT | CONTAINS_SET_INT | CONTAINS_SPAN_BIGINT | CONTAINS_SPAN_FLOAT | CONTAINS_SPAN_INT | CONTAINS_SPANSET_BIGINT | CONTAINS_SPANSET_FLOAT | CONTAINS_SPANSET_INT | CONTAINS_TBOX_TBOX | DISTANCE_SET_INT | DISTANCE_SPAN_INT | DISTANCE_SPANSET_INT | INTERSECTION_FLOAT_SET | INTERSECTION_INT_SET | INTERSECTION_SET_BIGINT | INTERSECTION_SET_FLOAT | INTERSECTION_SET_INT | INTERSECTION_SPAN_BIGINT | INTERSECTION_SPAN_FLOAT | INTERSECTION_SPAN_INT | INTERSECTION_SPANSET_BIGINT | INTERSECTION_SPANSET_FLOAT | INTERSECTION_SPANSET_INT | INTERSECTION_STBOX_STBOX | INTERSECTION_TBOX_TBOX | LEFT_BIGINT_SET | LEFT_BIGINT_SPAN | LEFT_BIGINT_SPANSET | LEFT_FLOAT_SET | LEFT_FLOAT_SPAN | LEFT_FLOAT_SPANSET | LEFT_INT_SET | LEFT_INT_SPAN | LEFT_INT_SPANSET | LEFT_SET_BIGINT | LEFT_SET_FLOAT | LEFT_SET_INT | LEFT_SPAN_BIGINT | LEFT_SPAN_FLOAT | LEFT_SPAN_INT | LEFT_SPANSET_BIGINT | LEFT_SPANSET_FLOAT | LEFT_SPANSET_INT | LEFT_TBOX_TBOX | MINUS_BIGINT_SET | MINUS_BIGINT_SPAN | MINUS_BIGINT_SPANSET | MINUS_FLOAT_SET | MINUS_FLOAT_SPAN | MINUS_FLOAT_SPANSET | MINUS_INT_SET | MINUS_INT_SPAN | MINUS_INT_SPANSET | MINUS_SET_BIGINT | MINUS_SET_FLOAT | MINUS_SET_INT | MINUS_SPAN_BIGINT | MINUS_SPAN_FLOAT | MINUS_SPAN_INT | MINUS_SPANSET_BIGINT | MINUS_SPANSET_FLOAT | MINUS_SPANSET_INT | NAD_TBOXINT_TBOXINT | OVERAFTER_TBOX_TBOX | OVERBEFORE_TBOX_TBOX | OVERLAPS_TBOX_TBOX | OVERLEFT_BIGINT_SET | OVERLEFT_BIGINT_SPAN | OVERLEFT_BIGINT_SPANSET | OVERLEFT_FLOAT_SET | OVERLEFT_FLOAT_SPAN | OVERLEFT_FLOAT_SPANSET | OVERLEFT_INT_SET | OVERLEFT_INT_SPAN | OVERLEFT_INT_SPANSET | OVERLEFT_SET_BIGINT | OVERLEFT_SET_FLOAT | OVERLEFT_SET_INT | OVERLEFT_SPAN_BIGINT | OVERLEFT_SPAN_FLOAT | OVERLEFT_SPAN_INT | OVERLEFT_SPANSET_BIGINT | OVERLEFT_SPANSET_FLOAT | OVERLEFT_SPANSET_INT | OVERLEFT_TBOX_TBOX | OVERRIGHT_BIGINT_SET | OVERRIGHT_BIGINT_SPAN | OVERRIGHT_BIGINT_SPANSET | OVERRIGHT_FLOAT_SET | OVERRIGHT_FLOAT_SPAN | OVERRIGHT_FLOAT_SPANSET | OVERRIGHT_INT_SET | OVERRIGHT_INT_SPAN | OVERRIGHT_INT_SPANSET | OVERRIGHT_SET_BIGINT | OVERRIGHT_SET_FLOAT | OVERRIGHT_SET_INT | OVERRIGHT_SPAN_BIGINT | OVERRIGHT_SPAN_FLOAT | OVERRIGHT_SPAN_INT | OVERRIGHT_SPANSET_BIGINT | OVERRIGHT_SPANSET_FLOAT | OVERRIGHT_SPANSET_INT | OVERRIGHT_TBOX_TBOX | RIGHT_BIGINT_SET | RIGHT_BIGINT_SPAN | RIGHT_BIGINT_SPANSET | RIGHT_FLOAT_SET | RIGHT_FLOAT_SPAN | RIGHT_FLOAT_SPANSET | RIGHT_INT_SET | RIGHT_INT_SPAN | RIGHT_INT_SPANSET | RIGHT_SET_BIGINT | RIGHT_SET_FLOAT | RIGHT_SET_INT | RIGHT_SPAN_BIGINT | RIGHT_SPAN_FLOAT | RIGHT_SPAN_INT | RIGHT_SPANSET_BIGINT | RIGHT_SPANSET_FLOAT | RIGHT_SPANSET_INT | RIGHT_TBOX_TBOX | SAME_TBOX_TBOX | TBOX_EQ | TBOX_GE | TBOX_GT | TBOX_LE | TBOX_LT | TBOX_NE | UNION_BIGINT_SET | UNION_BIGINT_SPAN | UNION_BIGINT_SPANSET | UNION_FLOAT_SET | UNION_FLOAT_SPAN | UNION_FLOAT_SPANSET | UNION_INT_SET | UNION_INT_SPAN | UNION_INT_SPANSET | UNION_SET_BIGINT | UNION_SET_FLOAT | UNION_SET_INT | UNION_SPAN_BIGINT | UNION_SPAN_FLOAT | UNION_SPAN_INT | UNION_SPANSET_BIGINT | UNION_SPANSET_FLOAT | UNION_SPANSET_INT | ADJACENT_SPAN_DATE | ADJACENT_SPAN_SPANSET | ADJACENT_SPAN_TIMESTAMPTZ | ADJACENT_SPANSET_DATE | ADJACENT_SPANSET_TIMESTAMPTZ | AFTER_DATE_SPAN | AFTER_DATE_SPANSET | AFTER_SET_DATE | AFTER_SET_TIMESTAMPTZ | AFTER_SPAN_DATE | AFTER_SPAN_TIMESTAMPTZ | AFTER_SPANSET_DATE | AFTER_SPANSET_TIMESTAMPTZ | AFTER_TIMESTAMPTZ_SET | AFTER_TIMESTAMPTZ_SPAN | AFTER_TIMESTAMPTZ_SPANSET | BEFORE_DATE_SET | BEFORE_DATE_SPAN | BEFORE_DATE_SPANSET | BEFORE_SET_DATE | BEFORE_SET_TIMESTAMPTZ | BEFORE_SPAN_DATE | BEFORE_SPAN_TIMESTAMPTZ | BEFORE_SPANSET_DATE | BEFORE_SPANSET_TIMESTAMPTZ | BEFORE_TIMESTAMPTZ_SET | BEFORE_TIMESTAMPTZ_SPAN | BEFORE_TIMESTAMPTZ_SPANSET | CONTAINED_DATE_SET | CONTAINED_DATE_SPAN | CONTAINED_DATE_SPANSET | CONTAINED_SPAN_SPANSET | CONTAINED_TIMESTAMPTZ_SET | CONTAINED_TIMESTAMPTZ_SPAN | CONTAINED_TIMESTAMPTZ_SPANSET | CONTAINS_SET_DATE | CONTAINS_SET_TIMESTAMPTZ | CONTAINS_SPAN_DATE | CONTAINS_SPAN_SPANSET | CONTAINS_SPAN_TIMESTAMPTZ | CONTAINS_SPANSET_DATE | CONTAINS_SPANSET_TIMESTAMPTZ | LEFT_SPAN_SPANSET | OVERAFTER_DATE_SET | OVERAFTER_DATE_SPAN | OVERAFTER_DATE_SPANSET | OVERAFTER_SET_DATE | OVERAFTER_SET_TIMESTAMPTZ | OVERAFTER_SPAN_DATE | OVERAFTER_SPAN_TIMESTAMPTZ | OVERAFTER_SPANSET_DATE | OVERAFTER_SPANSET_TIMESTAMPTZ | OVERAFTER_TIMESTAMPTZ_SET | OVERAFTER_TIMESTAMPTZ_SPAN | OVERAFTER_TIMESTAMPTZ_SPANSET | OVERBEFORE_DATE_SET | OVERBEFORE_DATE_SPAN | OVERBEFORE_DATE_SPANSET | OVERBEFORE_SET_DATE | OVERBEFORE_SET_TIMESTAMPTZ | OVERBEFORE_SPAN_DATE | OVERBEFORE_SPAN_TIMESTAMPTZ | OVERBEFORE_SPANSET_DATE | OVERBEFORE_SPANSET_TIMESTAMPTZ | OVERBEFORE_TIMESTAMPTZ_SET | OVERBEFORE_TIMESTAMPTZ_SPAN | OVERBEFORE_TIMESTAMPTZ_SPANSET | OVERLAPS_SPAN_SPANSET | OVERLEFT_SPAN_SPANSET | OVERRIGHT_SPAN_SPANSET | RIGHT_SPAN_SPANSET | INTSPAN_LOWER | INTSPAN_UPPER | INTSPAN_WIDTH | BIGINTSPAN_LOWER | BIGINTSPAN_UPPER | BIGINTSPAN_WIDTH | FLOATSPAN_LOWER | FLOATSPAN_UPPER | FLOATSPAN_WIDTH | DATESPAN_LOWER | DATESPAN_UPPER | TSTZSPAN_LOWER | TSTZSPAN_UPPER | INTSPANSET_LOWER | INTSPANSET_UPPER | BIGINTSPANSET_LOWER | BIGINTSPANSET_UPPER | FLOATSPANSET_LOWER | FLOATSPANSET_UPPER | TSTZSPANSET_LOWER | TSTZSPANSET_UPPER | INTSET_START_VALUE | INTSET_END_VALUE | BIGINTSET_START_VALUE | BIGINTSET_END_VALUE | FLOATSET_START_VALUE | FLOATSET_END_VALUE | DATESET_START_VALUE | DATESET_END_VALUE | TSTZSET_START_VALUE | TSTZSET_END_VALUE | SPAN_LOWER_INC | SPAN_UPPER_INC | SPANSET_LOWER_INC | SPANSET_UPPER_INC | SET_NUM_VALUES | SPANSET_NUM_SPANS;

sinkClause: INTO sink (',' sink)*;

sink: identifier | inlineSink;

inlineSink
    : type=identifier '(' parameters=namedConfigExpressionSeq ')'
    ;

nullNotnull
    : NOT? NULLTOKEN
    ;

streamName: IDENTIFIER;

fileFormat: CSV_FORMAT;

sortItem
    : expression ordering=(ASC | DESC)? (NULLS nullOrder=(LAST | FIRST))?
    ;

predicate
    : NOT? kind=BETWEEN lower=valueExpression AND upper=valueExpression
    | NOT? kind=IN '(' expression (',' expression)* ')'
    | NOT? kind=IN '(' query ')'
    | NOT? kind=RLIKE pattern=valueExpression
    | NOT? kind=LIKE quantifier=(ANY | SOME | ALL) ('('')' | '(' expression (',' expression)* ')')
    | NOT? kind=LIKE pattern=valueExpression (ESCAPE escapeChar=STRING)?
    | IS nullNotnull
    | IS NOT? kind=(TRUE | FALSE | UNKNOWN)
    | IS NOT? kind=DISTINCT FROM right=valueExpression
    ;


valueExpression
    : (functionName | typeDefinition) '(' (argument+=expression (',' argument+=expression)*)? ')'                 #functionCall
    | op=(MINUS | PLUS | TILDE) valueExpression                                        #arithmeticUnary
    | left=valueExpression op=(ASTERISK | SLASH | PERCENT | DIV) right=valueExpression #arithmeticBinary
    | left=valueExpression op=(PLUS | MINUS | CONCAT_PIPE) right=valueExpression       #arithmeticBinary
    | left=valueExpression op=AMPERSAND right=valueExpression                          #arithmeticBinary
    | left=valueExpression op=HAT right=valueExpression                                #arithmeticBinary
    | left=valueExpression op=PIPE right=valueExpression                               #arithmeticBinary
    | left=valueExpression comparisonOperator right=valueExpression                          #comparison
    | primaryExpression                                                                      #valueExpressionDefault
    ;

comparisonOperator
    : EQ | NEQ | NEQJ | LT | LTE | GT | GTE | NSEQ
    ;

hint
    : '/*+' hintStatements+=hintStatement (','? hintStatements+=hintStatement)* '*/'
    ;

hintStatement
    : hintName=identifier
    | hintName=identifier '(' parameters+=primaryExpression (',' parameters+=primaryExpression)* ')'
    ;

primaryExpression
    : ASTERISK                                                                                 #star
    | qualifiedName '.' ASTERISK                                                               #star
    | base=primaryExpression '.' fieldName=identifier                                          #dereference
    | '(' query ')'                                                                            #subqueryExpression
    | '(' namedExpression (',' namedExpression)+ ')'                                           #rowConstructor
    | '(' expression ')'                                                                       #parenthesizedExpression
    | constant                                                                                 #constantDefault
    | identifier                                                                               #columnReference
    ;

qualifiedName
    : identifier ('.' identifier)*
    ;

number
    : MINUS? INTEGER_VALUE              #integerLiteral
    | MINUS? FLOAT_LITERAL              #floatLiteral
    ;

unsignedIntegerLiteral: INTEGER_VALUE;

signedIntegerLiteral: MINUS INTEGER_VALUE;

constant
    : NULLTOKEN                                                                                #nullLiteral
    | identifier STRING                                                                        #typeConstructor
    | number                                                                                   #numericLiteral
    | booleanValue                                                                             #booleanLiteral
    | STRING                                                                                  #stringLiteral
    ;

booleanValue
    : TRUE | FALSE
    ;


ALL: 'ALL' | 'all';
AND: 'AND' | 'and';
ANY: 'ANY';
AS: 'AS' | 'as';
ASC: 'ASC' | 'asc';
AT: 'AT';
BETWEEN: 'BETWEEN' | 'between';
BY: 'BY' | 'by';
COMMENT: 'COMMENT';
CUBE: 'CUBE';
DELETE: 'DELETE';
DESC: 'DESC' | 'desc';
DISTINCT: 'DISTINCT';
DIV: 'DIV';
DROP: 'DROP';
ELSE: 'ELSE';
END: 'END';
ESCAPE: 'ESCAPE';
EXISTS: 'EXISTS';
FALSE: 'FALSE';
FIRST: 'FIRST';
FOR: 'FOR';
FROM: 'FROM' | 'from';
FULL: 'FULL';
GROUP: 'GROUP' | 'group';
GROUPING: 'GROUPING';
HAVING: 'HAVING' | 'having';
IF: 'IF';
IN: 'IN' | 'in';
INNER: 'INNER' | 'inner';
INSERT: 'INSERT' | 'insert';
INTO: 'INTO' | 'into';
IS: 'IS'  'is';
JOIN: 'JOIN' | 'join';
LAST: 'LAST';
LEFT: 'LEFT';
LIKE: 'LIKE';
LIMIT: 'LIMIT' | 'limit';
LIST: 'LIST';
MERGE: 'MERGE' | 'merge';
NATURAL: 'NATURAL';
NOT: 'NOT' | 'not' | '!';
NULLTOKEN:'NULL';
NULLS: 'NULLS';
OF: 'OF';
ON: 'ON' | 'on';
OR: 'OR' | 'or';
ORDER: 'ORDER' | 'order';
QUERY: 'QUERY';
RECOVER: 'RECOVER';
RIGHT: 'RIGHT';
RLIKE: 'RLIKE' | 'REGEXP';
ROLLUP: 'ROLLUP';
SCHEMA: 'SCHEMA';
SELECT: 'SELECT' | 'select';
SETS: 'SETS';
SOME: 'SOME';
START: 'START';
TABLE: 'TABLE';
TO: 'TO';
TRUE: 'TRUE';
TYPE: 'TYPE';
UNION: 'UNION' | 'union';
UNKNOWN: 'UNKNOWN';
USE: 'USE';
USING: 'USING';
VALUES: 'VALUES';
WHEN: 'WHEN';
WHERE: 'WHERE' | 'where';
WINDOW: 'WINDOW' | 'window';
WITH: 'WITH';
SET: 'SET';
TUMBLING: 'TUMBLING' | 'tumbling';
SLIDING: 'SLIDING' | 'sliding';
THRESHOLD : 'THRESHOLD'|'threshold';
SIZE: 'SIZE' | 'size';
ADVANCE: 'ADVANCE' | 'advance';
MS: 'MS' | 'ms';
SEC: 'SEC' | 'sec';
MINUTE: 'MINUTE' | 'minute' | 'MINUTES' | 'minutes';
HOUR: 'HOUR' | 'hour' | 'HOURS' | 'hours';
DAY: 'DAY' | 'day' | 'DAYS' | 'days';
MIN: 'MIN' | 'min';
MAX: 'MAX' | 'max';
AVG: 'AVG' | 'avg';
SUM: 'SUM' | 'sum';
COUNT: 'COUNT' | 'count';
MEDIAN: 'MEDIAN' | 'median';
VAR: 'VAR' | 'var';
ARRAY_AGG: 'ARRAY_AGG' | 'array_agg';
TEMPORAL_SEQUENCE: 'TEMPORAL_SEQUENCE' | 'temporal_sequence';
TEMPORAL_LENGTH: 'TEMPORAL_LENGTH' | 'temporal_length';
PAIR_MEETING: 'PAIR_MEETING' | 'pair_meeting';
CROSS_DISTANCE: 'CROSS_DISTANCE' | 'cross_distance';
TEMPORAL_EINTERSECTS_GEOMETRY: 'TEMPORAL_EINTERSECTS_GEOMETRY' | 'temporal_eintersects_geometry';
TEMPORAL_AINTERSECTS_GEOMETRY: 'TEMPORAL_AINTERSECTS_GEOMETRY' | 'temporal_aintersects_geometry';
TEMPORAL_ECONTAINS_GEOMETRY: 'TEMPORAL_ECONTAINS_GEOMETRY' | 'temporal_econtains_geometry';
EDWITHIN_TGEO_GEO: 'EDWITHIN_TGEO_GEO' | 'edwithin_tgeo_geo';
TGEO_AT_STBOX: 'TGEO_AT_STBOX' | 'tgeo_at_stbox';
/* BEGIN CODEGEN LEXER TOKENS */
TEMPORAL_ADISJOINT_GEOMETRY: 'TEMPORAL_ADISJOINT_GEOMETRY' | 'temporal_adisjoint_geometry';
TEMPORAL_ECONTAINS_TGEOMETRY: 'TEMPORAL_ECONTAINS_TGEOMETRY' | 'temporal_econtains_tgeometry';
TEMPORAL_ECOVERS_TGEOMETRY: 'TEMPORAL_ECOVERS_TGEOMETRY' | 'temporal_ecovers_tgeometry';
TEMPORAL_EDISJOINT_TGEOMETRY: 'TEMPORAL_EDISJOINT_TGEOMETRY' | 'temporal_edisjoint_tgeometry';
TEMPORAL_EINTERSECTS_TGEOMETRY: 'TEMPORAL_EINTERSECTS_TGEOMETRY' | 'temporal_eintersects_tgeometry';
TEMPORAL_ETOUCHES_TGEOMETRY: 'TEMPORAL_ETOUCHES_TGEOMETRY' | 'temporal_etouches_tgeometry';
TEMPORAL_ACONTAINS_TGEOMETRY: 'TEMPORAL_ACONTAINS_TGEOMETRY' | 'temporal_acontains_tgeometry';
TEMPORAL_ADISJOINT_TGEOMETRY: 'TEMPORAL_ADISJOINT_TGEOMETRY' | 'temporal_adisjoint_tgeometry';
TEMPORAL_AINTERSECTS_TGEOMETRY: 'TEMPORAL_AINTERSECTS_TGEOMETRY' | 'temporal_aintersects_tgeometry';
TEMPORAL_ATOUCHES_TGEOMETRY: 'TEMPORAL_ATOUCHES_TGEOMETRY' | 'temporal_atouches_tgeometry';
TEMPORAL_NAD_GEOMETRY: 'TEMPORAL_NAD_GEOMETRY' | 'temporal_nad_geometry';
TEMPORAL_NAD_TGEOMETRY: 'TEMPORAL_NAD_TGEOMETRY' | 'temporal_nad_tgeometry';
TEMPORAL_EDWITHIN_TGEOMETRY: 'TEMPORAL_EDWITHIN_TGEOMETRY' | 'temporal_edwithin_tgeometry';
TEMPORAL_ADWITHIN_GEOMETRY: 'TEMPORAL_ADWITHIN_GEOMETRY' | 'temporal_adwithin_geometry';
TEMPORAL_ADWITHIN_TGEOMETRY: 'TEMPORAL_ADWITHIN_TGEOMETRY' | 'temporal_adwithin_tgeometry';
TEMPORAL_EDISJOINT_GEOMETRY: 'TEMPORAL_EDISJOINT_GEOMETRY' | 'temporal_edisjoint_geometry';
TEMPORAL_ATOUCHES_GEOMETRY: 'TEMPORAL_ATOUCHES_GEOMETRY' | 'temporal_atouches_geometry';
TEMPORAL_ECOVERS_GEOMETRY: 'TEMPORAL_ECOVERS_GEOMETRY' | 'temporal_ecovers_geometry';
TEMPORAL_ACONTAINS_GEOMETRY: 'TEMPORAL_ACONTAINS_GEOMETRY' | 'temporal_acontains_geometry';
TEMPORAL_ETOUCHES_GEOMETRY: 'TEMPORAL_ETOUCHES_GEOMETRY' | 'temporal_etouches_geometry';
TEMPORAL_NAD_FLOAT_SCALAR: 'TEMPORAL_NAD_FLOAT_SCALAR' | 'temporal_nad_float_scalar';
TEMPORAL_NAD_INT_SCALAR: 'TEMPORAL_NAD_INT_SCALAR' | 'temporal_nad_int_scalar';
TEMPORAL_NAD_TFLOAT: 'TEMPORAL_NAD_TFLOAT' | 'temporal_nad_tfloat';
TEMPORAL_NAD_TINT: 'TEMPORAL_NAD_TINT' | 'temporal_nad_tint';
TEMPORAL_AT_GEOMETRY: 'TEMPORAL_AT_GEOMETRY' | 'temporal_at_geometry';
TEMPORAL_MINUS_GEOMETRY: 'TEMPORAL_MINUS_GEOMETRY' | 'temporal_minus_geometry';
TEMPORAL_ECONTAINS_TCBUFFER: 'TEMPORAL_ECONTAINS_TCBUFFER' | 'temporal_econtains_tcbuffer';
TEMPORAL_ECOVERS_TCBUFFER: 'TEMPORAL_ECOVERS_TCBUFFER' | 'temporal_ecovers_tcbuffer';
TEMPORAL_EDISJOINT_TCBUFFER: 'TEMPORAL_EDISJOINT_TCBUFFER' | 'temporal_edisjoint_tcbuffer';
TEMPORAL_EINTERSECTS_TCBUFFER: 'TEMPORAL_EINTERSECTS_TCBUFFER' | 'temporal_eintersects_tcbuffer';
TEMPORAL_ETOUCHES_TCBUFFER: 'TEMPORAL_ETOUCHES_TCBUFFER' | 'temporal_etouches_tcbuffer';
TEMPORAL_ACONTAINS_TCBUFFER: 'TEMPORAL_ACONTAINS_TCBUFFER' | 'temporal_acontains_tcbuffer';
TEMPORAL_ACOVERS_TCBUFFER: 'TEMPORAL_ACOVERS_TCBUFFER' | 'temporal_acovers_tcbuffer';
TEMPORAL_ADISJOINT_TCBUFFER: 'TEMPORAL_ADISJOINT_TCBUFFER' | 'temporal_adisjoint_tcbuffer';
TEMPORAL_AINTERSECTS_TCBUFFER: 'TEMPORAL_AINTERSECTS_TCBUFFER' | 'temporal_aintersects_tcbuffer';
TEMPORAL_ATOUCHES_TCBUFFER: 'TEMPORAL_ATOUCHES_TCBUFFER' | 'temporal_atouches_tcbuffer';
TEMPORAL_ECONTAINS_TCBUFFER_CBUFFER: 'TEMPORAL_ECONTAINS_TCBUFFER_CBUFFER' | 'temporal_econtains_tcbuffer_cbuffer';
TEMPORAL_ECOVERS_TCBUFFER_CBUFFER: 'TEMPORAL_ECOVERS_TCBUFFER_CBUFFER' | 'temporal_ecovers_tcbuffer_cbuffer';
TEMPORAL_EDISJOINT_TCBUFFER_CBUFFER: 'TEMPORAL_EDISJOINT_TCBUFFER_CBUFFER' | 'temporal_edisjoint_tcbuffer_cbuffer';
TEMPORAL_EINTERSECTS_TCBUFFER_CBUFFER: 'TEMPORAL_EINTERSECTS_TCBUFFER_CBUFFER' | 'temporal_eintersects_tcbuffer_cbuffer';
TEMPORAL_ETOUCHES_TCBUFFER_CBUFFER: 'TEMPORAL_ETOUCHES_TCBUFFER_CBUFFER' | 'temporal_etouches_tcbuffer_cbuffer';
TEMPORAL_ACONTAINS_TCBUFFER_CBUFFER: 'TEMPORAL_ACONTAINS_TCBUFFER_CBUFFER' | 'temporal_acontains_tcbuffer_cbuffer';
TEMPORAL_ACOVERS_TCBUFFER_CBUFFER: 'TEMPORAL_ACOVERS_TCBUFFER_CBUFFER' | 'temporal_acovers_tcbuffer_cbuffer';
TEMPORAL_ADISJOINT_TCBUFFER_CBUFFER: 'TEMPORAL_ADISJOINT_TCBUFFER_CBUFFER' | 'temporal_adisjoint_tcbuffer_cbuffer';
TEMPORAL_AINTERSECTS_TCBUFFER_CBUFFER: 'TEMPORAL_AINTERSECTS_TCBUFFER_CBUFFER' | 'temporal_aintersects_tcbuffer_cbuffer';
TEMPORAL_ATOUCHES_TCBUFFER_CBUFFER: 'TEMPORAL_ATOUCHES_TCBUFFER_CBUFFER' | 'temporal_atouches_tcbuffer_cbuffer';
TEMPORAL_ADISJOINT_TCBUFFER_TCBUFFER: 'TEMPORAL_ADISJOINT_TCBUFFER_TCBUFFER' | 'temporal_adisjoint_tcbuffer_tcbuffer';
TEMPORAL_AINTERSECTS_TCBUFFER_TCBUFFER: 'TEMPORAL_AINTERSECTS_TCBUFFER_TCBUFFER' | 'temporal_aintersects_tcbuffer_tcbuffer';
TEMPORAL_ATOUCHES_TCBUFFER_TCBUFFER: 'TEMPORAL_ATOUCHES_TCBUFFER_TCBUFFER' | 'temporal_atouches_tcbuffer_tcbuffer';
TEMPORAL_ECOVERS_TCBUFFER_TCBUFFER: 'TEMPORAL_ECOVERS_TCBUFFER_TCBUFFER' | 'temporal_ecovers_tcbuffer_tcbuffer';
TEMPORAL_EINTERSECTS_TCBUFFER_TCBUFFER: 'TEMPORAL_EINTERSECTS_TCBUFFER_TCBUFFER' | 'temporal_eintersects_tcbuffer_tcbuffer';
TEMPORAL_ETOUCHES_TCBUFFER_TCBUFFER: 'TEMPORAL_ETOUCHES_TCBUFFER_TCBUFFER' | 'temporal_etouches_tcbuffer_tcbuffer';
TEMPORAL_EDWITHIN_TCBUFFER_GEOMETRY: 'TEMPORAL_EDWITHIN_TCBUFFER_GEOMETRY' | 'temporal_edwithin_tcbuffer_geometry';
TEMPORAL_ADWITHIN_TCBUFFER_GEOMETRY: 'TEMPORAL_ADWITHIN_TCBUFFER_GEOMETRY' | 'temporal_adwithin_tcbuffer_geometry';
TEMPORAL_EDWITHIN_TCBUFFER_CBUFFER: 'TEMPORAL_EDWITHIN_TCBUFFER_CBUFFER' | 'temporal_edwithin_tcbuffer_cbuffer';
TEMPORAL_ADWITHIN_TCBUFFER_CBUFFER: 'TEMPORAL_ADWITHIN_TCBUFFER_CBUFFER' | 'temporal_adwithin_tcbuffer_cbuffer';
TEMPORAL_EDWITHIN_TCBUFFER_TCBUFFER: 'TEMPORAL_EDWITHIN_TCBUFFER_TCBUFFER' | 'temporal_edwithin_tcbuffer_tcbuffer';
TEMPORAL_ADWITHIN_TCBUFFER_TCBUFFER: 'TEMPORAL_ADWITHIN_TCBUFFER_TCBUFFER' | 'temporal_adwithin_tcbuffer_tcbuffer';
TEMPORAL_ECONTAINS_TPOSE_GEOMETRY: 'TEMPORAL_ECONTAINS_TPOSE_GEOMETRY' | 'temporal_econtains_tpose_geometry';
TEMPORAL_ECOVERS_TPOSE_GEOMETRY: 'TEMPORAL_ECOVERS_TPOSE_GEOMETRY' | 'temporal_ecovers_tpose_geometry';
TEMPORAL_EDISJOINT_TPOSE_GEOMETRY: 'TEMPORAL_EDISJOINT_TPOSE_GEOMETRY' | 'temporal_edisjoint_tpose_geometry';
TEMPORAL_EINTERSECTS_TPOSE_GEOMETRY: 'TEMPORAL_EINTERSECTS_TPOSE_GEOMETRY' | 'temporal_eintersects_tpose_geometry';
TEMPORAL_ETOUCHES_TPOSE_GEOMETRY: 'TEMPORAL_ETOUCHES_TPOSE_GEOMETRY' | 'temporal_etouches_tpose_geometry';
TEMPORAL_ACONTAINS_TPOSE_GEOMETRY: 'TEMPORAL_ACONTAINS_TPOSE_GEOMETRY' | 'temporal_acontains_tpose_geometry';
TEMPORAL_ADISJOINT_TPOSE_GEOMETRY: 'TEMPORAL_ADISJOINT_TPOSE_GEOMETRY' | 'temporal_adisjoint_tpose_geometry';
TEMPORAL_AINTERSECTS_TPOSE_GEOMETRY: 'TEMPORAL_AINTERSECTS_TPOSE_GEOMETRY' | 'temporal_aintersects_tpose_geometry';
TEMPORAL_ATOUCHES_TPOSE_GEOMETRY: 'TEMPORAL_ATOUCHES_TPOSE_GEOMETRY' | 'temporal_atouches_tpose_geometry';
TEMPORAL_ECONTAINS_TPOSE_TPOSE: 'TEMPORAL_ECONTAINS_TPOSE_TPOSE' | 'temporal_econtains_tpose_tpose';
TEMPORAL_ECOVERS_TPOSE_TPOSE: 'TEMPORAL_ECOVERS_TPOSE_TPOSE' | 'temporal_ecovers_tpose_tpose';
TEMPORAL_EDISJOINT_TPOSE_TPOSE: 'TEMPORAL_EDISJOINT_TPOSE_TPOSE' | 'temporal_edisjoint_tpose_tpose';
TEMPORAL_EINTERSECTS_TPOSE_TPOSE: 'TEMPORAL_EINTERSECTS_TPOSE_TPOSE' | 'temporal_eintersects_tpose_tpose';
TEMPORAL_ETOUCHES_TPOSE_TPOSE: 'TEMPORAL_ETOUCHES_TPOSE_TPOSE' | 'temporal_etouches_tpose_tpose';
TEMPORAL_ACONTAINS_TPOSE_TPOSE: 'TEMPORAL_ACONTAINS_TPOSE_TPOSE' | 'temporal_acontains_tpose_tpose';
TEMPORAL_ADISJOINT_TPOSE_TPOSE: 'TEMPORAL_ADISJOINT_TPOSE_TPOSE' | 'temporal_adisjoint_tpose_tpose';
TEMPORAL_AINTERSECTS_TPOSE_TPOSE: 'TEMPORAL_AINTERSECTS_TPOSE_TPOSE' | 'temporal_aintersects_tpose_tpose';
TEMPORAL_ATOUCHES_TPOSE_TPOSE: 'TEMPORAL_ATOUCHES_TPOSE_TPOSE' | 'temporal_atouches_tpose_tpose';
TEMPORAL_ECONTAINS_TNPOINT_GEOMETRY: 'TEMPORAL_ECONTAINS_TNPOINT_GEOMETRY' | 'temporal_econtains_tnpoint_geometry';
TEMPORAL_ECONTAINS_TNPOINT_TNPOINT: 'TEMPORAL_ECONTAINS_TNPOINT_TNPOINT' | 'temporal_econtains_tnpoint_tnpoint';
TEMPORAL_ECOVERS_TNPOINT_GEOMETRY: 'TEMPORAL_ECOVERS_TNPOINT_GEOMETRY' | 'temporal_ecovers_tnpoint_geometry';
TEMPORAL_ECOVERS_TNPOINT_TNPOINT: 'TEMPORAL_ECOVERS_TNPOINT_TNPOINT' | 'temporal_ecovers_tnpoint_tnpoint';
TEMPORAL_EDISJOINT_TNPOINT_GEOMETRY: 'TEMPORAL_EDISJOINT_TNPOINT_GEOMETRY' | 'temporal_edisjoint_tnpoint_geometry';
TEMPORAL_EDISJOINT_TNPOINT_TNPOINT: 'TEMPORAL_EDISJOINT_TNPOINT_TNPOINT' | 'temporal_edisjoint_tnpoint_tnpoint';
TEMPORAL_EINTERSECTS_TNPOINT_GEOMETRY: 'TEMPORAL_EINTERSECTS_TNPOINT_GEOMETRY' | 'temporal_eintersects_tnpoint_geometry';
TEMPORAL_EINTERSECTS_TNPOINT_TNPOINT: 'TEMPORAL_EINTERSECTS_TNPOINT_TNPOINT' | 'temporal_eintersects_tnpoint_tnpoint';
TEMPORAL_ETOUCHES_TNPOINT_GEOMETRY: 'TEMPORAL_ETOUCHES_TNPOINT_GEOMETRY' | 'temporal_etouches_tnpoint_geometry';
TEMPORAL_ETOUCHES_TNPOINT_TNPOINT: 'TEMPORAL_ETOUCHES_TNPOINT_TNPOINT' | 'temporal_etouches_tnpoint_tnpoint';
TEMPORAL_ACONTAINS_TNPOINT_GEOMETRY: 'TEMPORAL_ACONTAINS_TNPOINT_GEOMETRY' | 'temporal_acontains_tnpoint_geometry';
TEMPORAL_ACONTAINS_TNPOINT_TNPOINT: 'TEMPORAL_ACONTAINS_TNPOINT_TNPOINT' | 'temporal_acontains_tnpoint_tnpoint';
TEMPORAL_ADISJOINT_TNPOINT_GEOMETRY: 'TEMPORAL_ADISJOINT_TNPOINT_GEOMETRY' | 'temporal_adisjoint_tnpoint_geometry';
TEMPORAL_ADISJOINT_TNPOINT_TNPOINT: 'TEMPORAL_ADISJOINT_TNPOINT_TNPOINT' | 'temporal_adisjoint_tnpoint_tnpoint';
TEMPORAL_AINTERSECTS_TNPOINT_GEOMETRY: 'TEMPORAL_AINTERSECTS_TNPOINT_GEOMETRY' | 'temporal_aintersects_tnpoint_geometry';
TEMPORAL_AINTERSECTS_TNPOINT_TNPOINT: 'TEMPORAL_AINTERSECTS_TNPOINT_TNPOINT' | 'temporal_aintersects_tnpoint_tnpoint';
TEMPORAL_ATOUCHES_TNPOINT_GEOMETRY: 'TEMPORAL_ATOUCHES_TNPOINT_GEOMETRY' | 'temporal_atouches_tnpoint_geometry';
TEMPORAL_ATOUCHES_TNPOINT_TNPOINT: 'TEMPORAL_ATOUCHES_TNPOINT_TNPOINT' | 'temporal_atouches_tnpoint_tnpoint';
TEMPORAL_NAD_TPOSE_GEOMETRY: 'TEMPORAL_NAD_TPOSE_GEOMETRY' | 'temporal_nad_tpose_geometry';
TEMPORAL_NAD_TPOSE_TPOSE: 'TEMPORAL_NAD_TPOSE_TPOSE' | 'temporal_nad_tpose_tpose';
TEMPORAL_NAD_TNPOINT_GEOMETRY: 'TEMPORAL_NAD_TNPOINT_GEOMETRY' | 'temporal_nad_tnpoint_geometry';
TEMPORAL_NAD_TNPOINT_TNPOINT: 'TEMPORAL_NAD_TNPOINT_TNPOINT' | 'temporal_nad_tnpoint_tnpoint';
TEMPORAL_EDWITHIN_TPOSE_GEOMETRY: 'TEMPORAL_EDWITHIN_TPOSE_GEOMETRY' | 'temporal_edwithin_tpose_geometry';
TEMPORAL_EDWITHIN_TPOSE_TPOSE: 'TEMPORAL_EDWITHIN_TPOSE_TPOSE' | 'temporal_edwithin_tpose_tpose';
TEMPORAL_EDWITHIN_TNPOINT_GEOMETRY: 'TEMPORAL_EDWITHIN_TNPOINT_GEOMETRY' | 'temporal_edwithin_tnpoint_geometry';
TEMPORAL_EDWITHIN_TNPOINT_TNPOINT: 'TEMPORAL_EDWITHIN_TNPOINT_TNPOINT' | 'temporal_edwithin_tnpoint_tnpoint';
TEMPORAL_ADWITHIN_TPOSE_GEOMETRY: 'TEMPORAL_ADWITHIN_TPOSE_GEOMETRY' | 'temporal_adwithin_tpose_geometry';
TEMPORAL_ADWITHIN_TPOSE_TPOSE: 'TEMPORAL_ADWITHIN_TPOSE_TPOSE' | 'temporal_adwithin_tpose_tpose';
TEMPORAL_ADWITHIN_TNPOINT_GEOMETRY: 'TEMPORAL_ADWITHIN_TNPOINT_GEOMETRY' | 'temporal_adwithin_tnpoint_geometry';
TEMPORAL_ADWITHIN_TNPOINT_TNPOINT: 'TEMPORAL_ADWITHIN_TNPOINT_TNPOINT' | 'temporal_adwithin_tnpoint_tnpoint';
TEMPORAL_NAD_TCBUFFER: 'TEMPORAL_NAD_TCBUFFER' | 'temporal_nad_tcbuffer';
TEMPORAL_NAD_TCBUFFER_CBUFFER: 'TEMPORAL_NAD_TCBUFFER_CBUFFER' | 'temporal_nad_tcbuffer_cbuffer';
TEMPORAL_NAD_TCBUFFER_TCBUFFER: 'TEMPORAL_NAD_TCBUFFER_TCBUFFER' | 'temporal_nad_tcbuffer_tcbuffer';
ALWAYS_EQ_TFLOAT_FLOAT: 'ALWAYS_EQ_TFLOAT_FLOAT' | 'always_eq_tfloat_float';
ALWAYS_EQ_TINT_INT: 'ALWAYS_EQ_TINT_INT' | 'always_eq_tint_int';
ALWAYS_GE_TFLOAT_FLOAT: 'ALWAYS_GE_TFLOAT_FLOAT' | 'always_ge_tfloat_float';
ALWAYS_GE_TINT_INT: 'ALWAYS_GE_TINT_INT' | 'always_ge_tint_int';
ALWAYS_GT_TFLOAT_FLOAT: 'ALWAYS_GT_TFLOAT_FLOAT' | 'always_gt_tfloat_float';
ALWAYS_GT_TINT_INT: 'ALWAYS_GT_TINT_INT' | 'always_gt_tint_int';
ALWAYS_LE_TFLOAT_FLOAT: 'ALWAYS_LE_TFLOAT_FLOAT' | 'always_le_tfloat_float';
ALWAYS_LE_TINT_INT: 'ALWAYS_LE_TINT_INT' | 'always_le_tint_int';
ALWAYS_LT_TFLOAT_FLOAT: 'ALWAYS_LT_TFLOAT_FLOAT' | 'always_lt_tfloat_float';
ALWAYS_LT_TINT_INT: 'ALWAYS_LT_TINT_INT' | 'always_lt_tint_int';
ALWAYS_NE_TFLOAT_FLOAT: 'ALWAYS_NE_TFLOAT_FLOAT' | 'always_ne_tfloat_float';
ALWAYS_NE_TINT_INT: 'ALWAYS_NE_TINT_INT' | 'always_ne_tint_int';
EVER_EQ_TFLOAT_FLOAT: 'EVER_EQ_TFLOAT_FLOAT' | 'ever_eq_tfloat_float';
EVER_EQ_TINT_INT: 'EVER_EQ_TINT_INT' | 'ever_eq_tint_int';
EVER_GE_TFLOAT_FLOAT: 'EVER_GE_TFLOAT_FLOAT' | 'ever_ge_tfloat_float';
EVER_GE_TINT_INT: 'EVER_GE_TINT_INT' | 'ever_ge_tint_int';
EVER_GT_TFLOAT_FLOAT: 'EVER_GT_TFLOAT_FLOAT' | 'ever_gt_tfloat_float';
EVER_GT_TINT_INT: 'EVER_GT_TINT_INT' | 'ever_gt_tint_int';
EVER_LE_TFLOAT_FLOAT: 'EVER_LE_TFLOAT_FLOAT' | 'ever_le_tfloat_float';
EVER_LE_TINT_INT: 'EVER_LE_TINT_INT' | 'ever_le_tint_int';
EVER_LT_TFLOAT_FLOAT: 'EVER_LT_TFLOAT_FLOAT' | 'ever_lt_tfloat_float';
EVER_LT_TINT_INT: 'EVER_LT_TINT_INT' | 'ever_lt_tint_int';
EVER_NE_TFLOAT_FLOAT: 'EVER_NE_TFLOAT_FLOAT' | 'ever_ne_tfloat_float';
EVER_NE_TINT_INT: 'EVER_NE_TINT_INT' | 'ever_ne_tint_int';
ALWAYS_EQ_FLOAT_TFLOAT: 'ALWAYS_EQ_FLOAT_TFLOAT' | 'always_eq_float_tfloat';
ALWAYS_EQ_INT_TINT: 'ALWAYS_EQ_INT_TINT' | 'always_eq_int_tint';
ALWAYS_EQ_TEMPORAL_TEMPORAL: 'ALWAYS_EQ_TEMPORAL_TEMPORAL' | 'always_eq_temporal_temporal';
ALWAYS_GE_FLOAT_TFLOAT: 'ALWAYS_GE_FLOAT_TFLOAT' | 'always_ge_float_tfloat';
ALWAYS_GE_INT_TINT: 'ALWAYS_GE_INT_TINT' | 'always_ge_int_tint';
ALWAYS_GE_TEMPORAL_TEMPORAL: 'ALWAYS_GE_TEMPORAL_TEMPORAL' | 'always_ge_temporal_temporal';
ALWAYS_GT_FLOAT_TFLOAT: 'ALWAYS_GT_FLOAT_TFLOAT' | 'always_gt_float_tfloat';
ALWAYS_GT_INT_TINT: 'ALWAYS_GT_INT_TINT' | 'always_gt_int_tint';
ALWAYS_GT_TEMPORAL_TEMPORAL: 'ALWAYS_GT_TEMPORAL_TEMPORAL' | 'always_gt_temporal_temporal';
ALWAYS_LE_FLOAT_TFLOAT: 'ALWAYS_LE_FLOAT_TFLOAT' | 'always_le_float_tfloat';
ALWAYS_LE_INT_TINT: 'ALWAYS_LE_INT_TINT' | 'always_le_int_tint';
ALWAYS_LE_TEMPORAL_TEMPORAL: 'ALWAYS_LE_TEMPORAL_TEMPORAL' | 'always_le_temporal_temporal';
ALWAYS_LT_FLOAT_TFLOAT: 'ALWAYS_LT_FLOAT_TFLOAT' | 'always_lt_float_tfloat';
ALWAYS_LT_INT_TINT: 'ALWAYS_LT_INT_TINT' | 'always_lt_int_tint';
ALWAYS_LT_TEMPORAL_TEMPORAL: 'ALWAYS_LT_TEMPORAL_TEMPORAL' | 'always_lt_temporal_temporal';
ALWAYS_NE_FLOAT_TFLOAT: 'ALWAYS_NE_FLOAT_TFLOAT' | 'always_ne_float_tfloat';
ALWAYS_NE_INT_TINT: 'ALWAYS_NE_INT_TINT' | 'always_ne_int_tint';
ALWAYS_NE_TEMPORAL_TEMPORAL: 'ALWAYS_NE_TEMPORAL_TEMPORAL' | 'always_ne_temporal_temporal';
EVER_EQ_FLOAT_TFLOAT: 'EVER_EQ_FLOAT_TFLOAT' | 'ever_eq_float_tfloat';
EVER_EQ_INT_TINT: 'EVER_EQ_INT_TINT' | 'ever_eq_int_tint';
EVER_EQ_TEMPORAL_TEMPORAL: 'EVER_EQ_TEMPORAL_TEMPORAL' | 'ever_eq_temporal_temporal';
EVER_GE_FLOAT_TFLOAT: 'EVER_GE_FLOAT_TFLOAT' | 'ever_ge_float_tfloat';
EVER_GE_INT_TINT: 'EVER_GE_INT_TINT' | 'ever_ge_int_tint';
EVER_GE_TEMPORAL_TEMPORAL: 'EVER_GE_TEMPORAL_TEMPORAL' | 'ever_ge_temporal_temporal';
EVER_GT_FLOAT_TFLOAT: 'EVER_GT_FLOAT_TFLOAT' | 'ever_gt_float_tfloat';
EVER_GT_INT_TINT: 'EVER_GT_INT_TINT' | 'ever_gt_int_tint';
EVER_GT_TEMPORAL_TEMPORAL: 'EVER_GT_TEMPORAL_TEMPORAL' | 'ever_gt_temporal_temporal';
EVER_LE_FLOAT_TFLOAT: 'EVER_LE_FLOAT_TFLOAT' | 'ever_le_float_tfloat';
EVER_LE_INT_TINT: 'EVER_LE_INT_TINT' | 'ever_le_int_tint';
EVER_LE_TEMPORAL_TEMPORAL: 'EVER_LE_TEMPORAL_TEMPORAL' | 'ever_le_temporal_temporal';
EVER_LT_FLOAT_TFLOAT: 'EVER_LT_FLOAT_TFLOAT' | 'ever_lt_float_tfloat';
EVER_LT_INT_TINT: 'EVER_LT_INT_TINT' | 'ever_lt_int_tint';
EVER_LT_TEMPORAL_TEMPORAL: 'EVER_LT_TEMPORAL_TEMPORAL' | 'ever_lt_temporal_temporal';
EVER_NE_FLOAT_TFLOAT: 'EVER_NE_FLOAT_TFLOAT' | 'ever_ne_float_tfloat';
EVER_NE_INT_TINT: 'EVER_NE_INT_TINT' | 'ever_ne_int_tint';
EVER_NE_TEMPORAL_TEMPORAL: 'EVER_NE_TEMPORAL_TEMPORAL' | 'ever_ne_temporal_temporal';
ALWAYS_EQ_TCBUFFER_CBUFFER: 'ALWAYS_EQ_TCBUFFER_CBUFFER' | 'always_eq_tcbuffer_cbuffer';
ALWAYS_EQ_TCBUFFER_TCBUFFER: 'ALWAYS_EQ_TCBUFFER_TCBUFFER' | 'always_eq_tcbuffer_tcbuffer';
ALWAYS_EQ_TGEO_GEO: 'ALWAYS_EQ_TGEO_GEO' | 'always_eq_tgeo_geo';
ALWAYS_EQ_TGEO_TGEO: 'ALWAYS_EQ_TGEO_TGEO' | 'always_eq_tgeo_tgeo';
ALWAYS_NE_TCBUFFER_CBUFFER: 'ALWAYS_NE_TCBUFFER_CBUFFER' | 'always_ne_tcbuffer_cbuffer';
ALWAYS_NE_TCBUFFER_TCBUFFER: 'ALWAYS_NE_TCBUFFER_TCBUFFER' | 'always_ne_tcbuffer_tcbuffer';
ALWAYS_NE_TGEO_GEO: 'ALWAYS_NE_TGEO_GEO' | 'always_ne_tgeo_geo';
ALWAYS_NE_TGEO_TGEO: 'ALWAYS_NE_TGEO_TGEO' | 'always_ne_tgeo_tgeo';
ATOUCHES_TPOINT_GEO: 'ATOUCHES_TPOINT_GEO' | 'atouches_tpoint_geo';
ETOUCHES_TPOINT_GEO: 'ETOUCHES_TPOINT_GEO' | 'etouches_tpoint_geo';
EVER_EQ_TCBUFFER_CBUFFER: 'EVER_EQ_TCBUFFER_CBUFFER' | 'ever_eq_tcbuffer_cbuffer';
EVER_EQ_TCBUFFER_TCBUFFER: 'EVER_EQ_TCBUFFER_TCBUFFER' | 'ever_eq_tcbuffer_tcbuffer';
EVER_EQ_TGEO_GEO: 'EVER_EQ_TGEO_GEO' | 'ever_eq_tgeo_geo';
EVER_EQ_TGEO_TGEO: 'EVER_EQ_TGEO_TGEO' | 'ever_eq_tgeo_tgeo';
EVER_NE_TCBUFFER_CBUFFER: 'EVER_NE_TCBUFFER_CBUFFER' | 'ever_ne_tcbuffer_cbuffer';
EVER_NE_TCBUFFER_TCBUFFER: 'EVER_NE_TCBUFFER_TCBUFFER' | 'ever_ne_tcbuffer_tcbuffer';
EVER_NE_TGEO_GEO: 'EVER_NE_TGEO_GEO' | 'ever_ne_tgeo_geo';
EVER_NE_TGEO_TGEO: 'EVER_NE_TGEO_TGEO' | 'ever_ne_tgeo_tgeo';
ABOVE_TSPATIAL_TSPATIAL: 'ABOVE_TSPATIAL_TSPATIAL' | 'above_tspatial_tspatial';
ADJACENT_TEMPORAL_TEMPORAL: 'ADJACENT_TEMPORAL_TEMPORAL' | 'adjacent_temporal_temporal';
ADJACENT_TSPATIAL_TSPATIAL: 'ADJACENT_TSPATIAL_TSPATIAL' | 'adjacent_tspatial_tspatial';
AFTER_TEMPORAL_TEMPORAL: 'AFTER_TEMPORAL_TEMPORAL' | 'after_temporal_temporal';
AFTER_TSPATIAL_TSPATIAL: 'AFTER_TSPATIAL_TSPATIAL' | 'after_tspatial_tspatial';
ALWAYS_EQ_TBOOL_BOOL: 'ALWAYS_EQ_TBOOL_BOOL' | 'always_eq_tbool_bool';
ALWAYS_NE_TBOOL_BOOL: 'ALWAYS_NE_TBOOL_BOOL' | 'always_ne_tbool_bool';
BACK_TSPATIAL_TSPATIAL: 'BACK_TSPATIAL_TSPATIAL' | 'back_tspatial_tspatial';
BEFORE_TEMPORAL_TEMPORAL: 'BEFORE_TEMPORAL_TEMPORAL' | 'before_temporal_temporal';
BEFORE_TSPATIAL_TSPATIAL: 'BEFORE_TSPATIAL_TSPATIAL' | 'before_tspatial_tspatial';
BELOW_TSPATIAL_TSPATIAL: 'BELOW_TSPATIAL_TSPATIAL' | 'below_tspatial_tspatial';
CONTAINED_TEMPORAL_TEMPORAL: 'CONTAINED_TEMPORAL_TEMPORAL' | 'contained_temporal_temporal';
CONTAINED_TSPATIAL_TSPATIAL: 'CONTAINED_TSPATIAL_TSPATIAL' | 'contained_tspatial_tspatial';
CONTAINS_TEMPORAL_TEMPORAL: 'CONTAINS_TEMPORAL_TEMPORAL' | 'contains_temporal_temporal';
CONTAINS_TSPATIAL_TSPATIAL: 'CONTAINS_TSPATIAL_TSPATIAL' | 'contains_tspatial_tspatial';
EVER_EQ_TBOOL_BOOL: 'EVER_EQ_TBOOL_BOOL' | 'ever_eq_tbool_bool';
EVER_NE_TBOOL_BOOL: 'EVER_NE_TBOOL_BOOL' | 'ever_ne_tbool_bool';
FRONT_TSPATIAL_TSPATIAL: 'FRONT_TSPATIAL_TSPATIAL' | 'front_tspatial_tspatial';
LEFT_TSPATIAL_TSPATIAL: 'LEFT_TSPATIAL_TSPATIAL' | 'left_tspatial_tspatial';
NAD_TNPOINT_GEO: 'NAD_TNPOINT_GEO' | 'nad_tnpoint_geo';
NAD_TPOSE_GEO: 'NAD_TPOSE_GEO' | 'nad_tpose_geo';
OVERABOVE_TSPATIAL_TSPATIAL: 'OVERABOVE_TSPATIAL_TSPATIAL' | 'overabove_tspatial_tspatial';
OVERAFTER_TEMPORAL_TEMPORAL: 'OVERAFTER_TEMPORAL_TEMPORAL' | 'overafter_temporal_temporal';
OVERAFTER_TSPATIAL_TSPATIAL: 'OVERAFTER_TSPATIAL_TSPATIAL' | 'overafter_tspatial_tspatial';
OVERBACK_TSPATIAL_TSPATIAL: 'OVERBACK_TSPATIAL_TSPATIAL' | 'overback_tspatial_tspatial';
OVERBEFORE_TEMPORAL_TEMPORAL: 'OVERBEFORE_TEMPORAL_TEMPORAL' | 'overbefore_temporal_temporal';
OVERBEFORE_TSPATIAL_TSPATIAL: 'OVERBEFORE_TSPATIAL_TSPATIAL' | 'overbefore_tspatial_tspatial';
OVERBELOW_TSPATIAL_TSPATIAL: 'OVERBELOW_TSPATIAL_TSPATIAL' | 'overbelow_tspatial_tspatial';
OVERFRONT_TSPATIAL_TSPATIAL: 'OVERFRONT_TSPATIAL_TSPATIAL' | 'overfront_tspatial_tspatial';
OVERLAPS_TEMPORAL_TEMPORAL: 'OVERLAPS_TEMPORAL_TEMPORAL' | 'overlaps_temporal_temporal';
OVERLAPS_TSPATIAL_TSPATIAL: 'OVERLAPS_TSPATIAL_TSPATIAL' | 'overlaps_tspatial_tspatial';
OVERLEFT_TSPATIAL_TSPATIAL: 'OVERLEFT_TSPATIAL_TSPATIAL' | 'overleft_tspatial_tspatial';
OVERRIGHT_TSPATIAL_TSPATIAL: 'OVERRIGHT_TSPATIAL_TSPATIAL' | 'overright_tspatial_tspatial';
RIGHT_TSPATIAL_TSPATIAL: 'RIGHT_TSPATIAL_TSPATIAL' | 'right_tspatial_tspatial';
SAME_TEMPORAL_TEMPORAL: 'SAME_TEMPORAL_TEMPORAL' | 'same_temporal_temporal';
SAME_TSPATIAL_TSPATIAL: 'SAME_TSPATIAL_TSPATIAL' | 'same_tspatial_tspatial';
TBOOL_END_VALUE: 'TBOOL_END_VALUE' | 'tbool_end_value';
TBOOL_START_VALUE: 'TBOOL_START_VALUE' | 'tbool_start_value';
TEMPORAL_CMP: 'TEMPORAL_CMP' | 'temporal_cmp';
TEMPORAL_DYNTIMEWARP_DISTANCE: 'TEMPORAL_DYNTIMEWARP_DISTANCE' | 'temporal_dyntimewarp_distance';
TEMPORAL_EQ: 'TEMPORAL_EQ' | 'temporal_eq';
TEMPORAL_FRECHET_DISTANCE: 'TEMPORAL_FRECHET_DISTANCE' | 'temporal_frechet_distance';
TEMPORAL_GE: 'TEMPORAL_GE' | 'temporal_ge';
TEMPORAL_GT: 'TEMPORAL_GT' | 'temporal_gt';
TEMPORAL_HAUSDORFF_DISTANCE: 'TEMPORAL_HAUSDORFF_DISTANCE' | 'temporal_hausdorff_distance';
TEMPORAL_LE: 'TEMPORAL_LE' | 'temporal_le';
TEMPORAL_LT: 'TEMPORAL_LT' | 'temporal_lt';
TEMPORAL_NE: 'TEMPORAL_NE' | 'temporal_ne';
TNPOINT_LENGTH: 'TNPOINT_LENGTH' | 'tnpoint_length';
TBOOL_TO_TINT: 'TBOOL_TO_TINT' | 'tbool_to_tint';
TCBUFFER_TO_TFLOAT: 'TCBUFFER_TO_TFLOAT' | 'tcbuffer_to_tfloat';
TFLOAT_CEIL: 'TFLOAT_CEIL' | 'tfloat_ceil';
TFLOAT_EXP: 'TFLOAT_EXP' | 'tfloat_exp';
TFLOAT_FLOOR: 'TFLOAT_FLOOR' | 'tfloat_floor';
TFLOAT_LN: 'TFLOAT_LN' | 'tfloat_ln';
TFLOAT_LOG10: 'TFLOAT_LOG10' | 'tfloat_log10';
TFLOAT_RADIANS: 'TFLOAT_RADIANS' | 'tfloat_radians';
TFLOAT_TO_TINT: 'TFLOAT_TO_TINT' | 'tfloat_to_tint';
TINT_TO_TFLOAT: 'TINT_TO_TFLOAT' | 'tint_to_tfloat';
ADJACENT_TNUMBER_TBOX: 'ADJACENT_TNUMBER_TBOX' | 'adjacent_tnumber_tbox';
AFTER_TNUMBER_TBOX: 'AFTER_TNUMBER_TBOX' | 'after_tnumber_tbox';
BEFORE_TNUMBER_TBOX: 'BEFORE_TNUMBER_TBOX' | 'before_tnumber_tbox';
CONTAINED_TNUMBER_TBOX: 'CONTAINED_TNUMBER_TBOX' | 'contained_tnumber_tbox';
CONTAINS_TNUMBER_TBOX: 'CONTAINS_TNUMBER_TBOX' | 'contains_tnumber_tbox';
LEFT_TNUMBER_TBOX: 'LEFT_TNUMBER_TBOX' | 'left_tnumber_tbox';
NAD_TCBUFFER_STBOX: 'NAD_TCBUFFER_STBOX' | 'nad_tcbuffer_stbox';
NAD_TFLOAT_TBOX: 'NAD_TFLOAT_TBOX' | 'nad_tfloat_tbox';
NAD_TGEO_STBOX: 'NAD_TGEO_STBOX' | 'nad_tgeo_stbox';
NAD_TINT_TBOX: 'NAD_TINT_TBOX' | 'nad_tint_tbox';
NAD_TNPOINT_STBOX: 'NAD_TNPOINT_STBOX' | 'nad_tnpoint_stbox';
NAD_TPOSE_STBOX: 'NAD_TPOSE_STBOX' | 'nad_tpose_stbox';
OVERAFTER_TNUMBER_TBOX: 'OVERAFTER_TNUMBER_TBOX' | 'overafter_tnumber_tbox';
OVERBEFORE_TNUMBER_TBOX: 'OVERBEFORE_TNUMBER_TBOX' | 'overbefore_tnumber_tbox';
OVERLAPS_TNUMBER_TBOX: 'OVERLAPS_TNUMBER_TBOX' | 'overlaps_tnumber_tbox';
OVERLEFT_TNUMBER_TBOX: 'OVERLEFT_TNUMBER_TBOX' | 'overleft_tnumber_tbox';
OVERRIGHT_TNUMBER_TBOX: 'OVERRIGHT_TNUMBER_TBOX' | 'overright_tnumber_tbox';
RIGHT_TNUMBER_TBOX: 'RIGHT_TNUMBER_TBOX' | 'right_tnumber_tbox';
SAME_TNUMBER_TBOX: 'SAME_TNUMBER_TBOX' | 'same_tnumber_tbox';
ABOVE_STBOX_TSPATIAL: 'ABOVE_STBOX_TSPATIAL' | 'above_stbox_tspatial';
ABOVE_TSPATIAL_STBOX: 'ABOVE_TSPATIAL_STBOX' | 'above_tspatial_stbox';
ADJACENT_STBOX_TSPATIAL: 'ADJACENT_STBOX_TSPATIAL' | 'adjacent_stbox_tspatial';
ADJACENT_TBOX_TNUMBER: 'ADJACENT_TBOX_TNUMBER' | 'adjacent_tbox_tnumber';
ADJACENT_TSPATIAL_STBOX: 'ADJACENT_TSPATIAL_STBOX' | 'adjacent_tspatial_stbox';
AFTER_STBOX_TSPATIAL: 'AFTER_STBOX_TSPATIAL' | 'after_stbox_tspatial';
AFTER_TBOX_TNUMBER: 'AFTER_TBOX_TNUMBER' | 'after_tbox_tnumber';
AFTER_TSPATIAL_STBOX: 'AFTER_TSPATIAL_STBOX' | 'after_tspatial_stbox';
BACK_STBOX_TSPATIAL: 'BACK_STBOX_TSPATIAL' | 'back_stbox_tspatial';
BACK_TSPATIAL_STBOX: 'BACK_TSPATIAL_STBOX' | 'back_tspatial_stbox';
BEFORE_STBOX_TSPATIAL: 'BEFORE_STBOX_TSPATIAL' | 'before_stbox_tspatial';
BEFORE_TBOX_TNUMBER: 'BEFORE_TBOX_TNUMBER' | 'before_tbox_tnumber';
BEFORE_TSPATIAL_STBOX: 'BEFORE_TSPATIAL_STBOX' | 'before_tspatial_stbox';
BELOW_STBOX_TSPATIAL: 'BELOW_STBOX_TSPATIAL' | 'below_stbox_tspatial';
BELOW_TSPATIAL_STBOX: 'BELOW_TSPATIAL_STBOX' | 'below_tspatial_stbox';
CONTAINED_STBOX_TSPATIAL: 'CONTAINED_STBOX_TSPATIAL' | 'contained_stbox_tspatial';
CONTAINED_TBOX_TNUMBER: 'CONTAINED_TBOX_TNUMBER' | 'contained_tbox_tnumber';
CONTAINED_TSPATIAL_STBOX: 'CONTAINED_TSPATIAL_STBOX' | 'contained_tspatial_stbox';
CONTAINS_STBOX_TSPATIAL: 'CONTAINS_STBOX_TSPATIAL' | 'contains_stbox_tspatial';
CONTAINS_TBOX_TNUMBER: 'CONTAINS_TBOX_TNUMBER' | 'contains_tbox_tnumber';
CONTAINS_TSPATIAL_STBOX: 'CONTAINS_TSPATIAL_STBOX' | 'contains_tspatial_stbox';
FRONT_STBOX_TSPATIAL: 'FRONT_STBOX_TSPATIAL' | 'front_stbox_tspatial';
FRONT_TSPATIAL_STBOX: 'FRONT_TSPATIAL_STBOX' | 'front_tspatial_stbox';
LEFT_STBOX_TSPATIAL: 'LEFT_STBOX_TSPATIAL' | 'left_stbox_tspatial';
LEFT_TBOX_TNUMBER: 'LEFT_TBOX_TNUMBER' | 'left_tbox_tnumber';
LEFT_TSPATIAL_STBOX: 'LEFT_TSPATIAL_STBOX' | 'left_tspatial_stbox';
OVERABOVE_STBOX_TSPATIAL: 'OVERABOVE_STBOX_TSPATIAL' | 'overabove_stbox_tspatial';
OVERABOVE_TSPATIAL_STBOX: 'OVERABOVE_TSPATIAL_STBOX' | 'overabove_tspatial_stbox';
OVERAFTER_STBOX_TSPATIAL: 'OVERAFTER_STBOX_TSPATIAL' | 'overafter_stbox_tspatial';
OVERAFTER_TBOX_TNUMBER: 'OVERAFTER_TBOX_TNUMBER' | 'overafter_tbox_tnumber';
OVERAFTER_TSPATIAL_STBOX: 'OVERAFTER_TSPATIAL_STBOX' | 'overafter_tspatial_stbox';
OVERBACK_STBOX_TSPATIAL: 'OVERBACK_STBOX_TSPATIAL' | 'overback_stbox_tspatial';
OVERBACK_TSPATIAL_STBOX: 'OVERBACK_TSPATIAL_STBOX' | 'overback_tspatial_stbox';
OVERBEFORE_STBOX_TSPATIAL: 'OVERBEFORE_STBOX_TSPATIAL' | 'overbefore_stbox_tspatial';
OVERBEFORE_TBOX_TNUMBER: 'OVERBEFORE_TBOX_TNUMBER' | 'overbefore_tbox_tnumber';
OVERBEFORE_TSPATIAL_STBOX: 'OVERBEFORE_TSPATIAL_STBOX' | 'overbefore_tspatial_stbox';
OVERBELOW_STBOX_TSPATIAL: 'OVERBELOW_STBOX_TSPATIAL' | 'overbelow_stbox_tspatial';
OVERBELOW_TSPATIAL_STBOX: 'OVERBELOW_TSPATIAL_STBOX' | 'overbelow_tspatial_stbox';
OVERFRONT_STBOX_TSPATIAL: 'OVERFRONT_STBOX_TSPATIAL' | 'overfront_stbox_tspatial';
OVERFRONT_TSPATIAL_STBOX: 'OVERFRONT_TSPATIAL_STBOX' | 'overfront_tspatial_stbox';
OVERLAPS_STBOX_TSPATIAL: 'OVERLAPS_STBOX_TSPATIAL' | 'overlaps_stbox_tspatial';
OVERLAPS_TBOX_TNUMBER: 'OVERLAPS_TBOX_TNUMBER' | 'overlaps_tbox_tnumber';
OVERLAPS_TSPATIAL_STBOX: 'OVERLAPS_TSPATIAL_STBOX' | 'overlaps_tspatial_stbox';
OVERLEFT_STBOX_TSPATIAL: 'OVERLEFT_STBOX_TSPATIAL' | 'overleft_stbox_tspatial';
OVERLEFT_TBOX_TNUMBER: 'OVERLEFT_TBOX_TNUMBER' | 'overleft_tbox_tnumber';
OVERLEFT_TSPATIAL_STBOX: 'OVERLEFT_TSPATIAL_STBOX' | 'overleft_tspatial_stbox';
OVERRIGHT_STBOX_TSPATIAL: 'OVERRIGHT_STBOX_TSPATIAL' | 'overright_stbox_tspatial';
OVERRIGHT_TBOX_TNUMBER: 'OVERRIGHT_TBOX_TNUMBER' | 'overright_tbox_tnumber';
OVERRIGHT_TSPATIAL_STBOX: 'OVERRIGHT_TSPATIAL_STBOX' | 'overright_tspatial_stbox';
RIGHT_STBOX_TSPATIAL: 'RIGHT_STBOX_TSPATIAL' | 'right_stbox_tspatial';
RIGHT_TBOX_TNUMBER: 'RIGHT_TBOX_TNUMBER' | 'right_tbox_tnumber';
RIGHT_TSPATIAL_STBOX: 'RIGHT_TSPATIAL_STBOX' | 'right_tspatial_stbox';
SAME_STBOX_TSPATIAL: 'SAME_STBOX_TSPATIAL' | 'same_stbox_tspatial';
SAME_TBOX_TNUMBER: 'SAME_TBOX_TNUMBER' | 'same_tbox_tnumber';
SAME_TSPATIAL_STBOX: 'SAME_TSPATIAL_STBOX' | 'same_tspatial_stbox';
TPOINT_LENGTH_WKB: 'TPOINT_LENGTH_WKB' | 'tpoint_length_wkb';
ABOVE_STBOX_STBOX: 'ABOVE_STBOX_STBOX' | 'above_stbox_stbox';
ADJACENT_STBOX_STBOX: 'ADJACENT_STBOX_STBOX' | 'adjacent_stbox_stbox';
AFTER_STBOX_STBOX: 'AFTER_STBOX_STBOX' | 'after_stbox_stbox';
BACK_STBOX_STBOX: 'BACK_STBOX_STBOX' | 'back_stbox_stbox';
BEFORE_STBOX_STBOX: 'BEFORE_STBOX_STBOX' | 'before_stbox_stbox';
BELOW_STBOX_STBOX: 'BELOW_STBOX_STBOX' | 'below_stbox_stbox';
CONTAINED_STBOX_STBOX: 'CONTAINED_STBOX_STBOX' | 'contained_stbox_stbox';
CONTAINS_STBOX_STBOX: 'CONTAINS_STBOX_STBOX' | 'contains_stbox_stbox';
FRONT_STBOX_STBOX: 'FRONT_STBOX_STBOX' | 'front_stbox_stbox';
LEFT_STBOX_STBOX: 'LEFT_STBOX_STBOX' | 'left_stbox_stbox';
NAD_STBOX_STBOX: 'NAD_STBOX_STBOX' | 'nad_stbox_stbox';
OVERABOVE_STBOX_STBOX: 'OVERABOVE_STBOX_STBOX' | 'overabove_stbox_stbox';
OVERAFTER_STBOX_STBOX: 'OVERAFTER_STBOX_STBOX' | 'overafter_stbox_stbox';
OVERBACK_STBOX_STBOX: 'OVERBACK_STBOX_STBOX' | 'overback_stbox_stbox';
OVERBEFORE_STBOX_STBOX: 'OVERBEFORE_STBOX_STBOX' | 'overbefore_stbox_stbox';
OVERBELOW_STBOX_STBOX: 'OVERBELOW_STBOX_STBOX' | 'overbelow_stbox_stbox';
OVERFRONT_STBOX_STBOX: 'OVERFRONT_STBOX_STBOX' | 'overfront_stbox_stbox';
OVERLAPS_STBOX_STBOX: 'OVERLAPS_STBOX_STBOX' | 'overlaps_stbox_stbox';
OVERLEFT_STBOX_STBOX: 'OVERLEFT_STBOX_STBOX' | 'overleft_stbox_stbox';
OVERRIGHT_STBOX_STBOX: 'OVERRIGHT_STBOX_STBOX' | 'overright_stbox_stbox';
RIGHT_STBOX_STBOX: 'RIGHT_STBOX_STBOX' | 'right_stbox_stbox';
SAME_STBOX_STBOX: 'SAME_STBOX_STBOX' | 'same_stbox_stbox';
STBOX_CMP: 'STBOX_CMP' | 'stbox_cmp';
STBOX_EQ: 'STBOX_EQ' | 'stbox_eq';
STBOX_GE: 'STBOX_GE' | 'stbox_ge';
STBOX_GT: 'STBOX_GT' | 'stbox_gt';
STBOX_LE: 'STBOX_LE' | 'stbox_le';
STBOX_LT: 'STBOX_LT' | 'stbox_lt';
STBOX_NE: 'STBOX_NE' | 'stbox_ne';
ADJACENT_TNUMBER_TNUMBER: 'ADJACENT_TNUMBER_TNUMBER' | 'adjacent_tnumber_tnumber';
AFTER_TNUMBER_TNUMBER: 'AFTER_TNUMBER_TNUMBER' | 'after_tnumber_tnumber';
BEFORE_TNUMBER_TNUMBER: 'BEFORE_TNUMBER_TNUMBER' | 'before_tnumber_tnumber';
CONTAINED_TNUMBER_TNUMBER: 'CONTAINED_TNUMBER_TNUMBER' | 'contained_tnumber_tnumber';
CONTAINS_TNUMBER_TNUMBER: 'CONTAINS_TNUMBER_TNUMBER' | 'contains_tnumber_tnumber';
LEFT_TNUMBER_TNUMBER: 'LEFT_TNUMBER_TNUMBER' | 'left_tnumber_tnumber';
OVERAFTER_TNUMBER_TNUMBER: 'OVERAFTER_TNUMBER_TNUMBER' | 'overafter_tnumber_tnumber';
OVERBEFORE_TNUMBER_TNUMBER: 'OVERBEFORE_TNUMBER_TNUMBER' | 'overbefore_tnumber_tnumber';
OVERLAPS_TNUMBER_TNUMBER: 'OVERLAPS_TNUMBER_TNUMBER' | 'overlaps_tnumber_tnumber';
OVERLEFT_TNUMBER_TNUMBER: 'OVERLEFT_TNUMBER_TNUMBER' | 'overleft_tnumber_tnumber';
OVERRIGHT_TNUMBER_TNUMBER: 'OVERRIGHT_TNUMBER_TNUMBER' | 'overright_tnumber_tnumber';
RIGHT_TNUMBER_TNUMBER: 'RIGHT_TNUMBER_TNUMBER' | 'right_tnumber_tnumber';
SAME_TNUMBER_TNUMBER: 'SAME_TNUMBER_TNUMBER' | 'same_tnumber_tnumber';
ALWAYS_EQ_TNPOINT_TNPOINT: 'ALWAYS_EQ_TNPOINT_TNPOINT' | 'always_eq_tnpoint_tnpoint';
ALWAYS_EQ_TPOSE_TPOSE: 'ALWAYS_EQ_TPOSE_TPOSE' | 'always_eq_tpose_tpose';
ALWAYS_NE_TNPOINT_TNPOINT: 'ALWAYS_NE_TNPOINT_TNPOINT' | 'always_ne_tnpoint_tnpoint';
ALWAYS_NE_TPOSE_TPOSE: 'ALWAYS_NE_TPOSE_TPOSE' | 'always_ne_tpose_tpose';
EVER_EQ_TNPOINT_TNPOINT: 'EVER_EQ_TNPOINT_TNPOINT' | 'ever_eq_tnpoint_tnpoint';
EVER_EQ_TPOSE_TPOSE: 'EVER_EQ_TPOSE_TPOSE' | 'ever_eq_tpose_tpose';
EVER_NE_TNPOINT_TNPOINT: 'EVER_NE_TNPOINT_TNPOINT' | 'ever_ne_tnpoint_tnpoint';
EVER_NE_TPOSE_TPOSE: 'EVER_NE_TPOSE_TPOSE' | 'ever_ne_tpose_tpose';
NAD_TNPOINT_TNPOINT: 'NAD_TNPOINT_TNPOINT' | 'nad_tnpoint_tnpoint';
NAD_TPOSE_TPOSE: 'NAD_TPOSE_TPOSE' | 'nad_tpose_tpose';
ADD_TNUMBER_TNUMBER: 'ADD_TNUMBER_TNUMBER' | 'add_tnumber_tnumber';
DIV_TNUMBER_TNUMBER: 'DIV_TNUMBER_TNUMBER' | 'div_tnumber_tnumber';
MUL_TNUMBER_TNUMBER: 'MUL_TNUMBER_TNUMBER' | 'mul_tnumber_tnumber';
SUB_TNUMBER_TNUMBER: 'SUB_TNUMBER_TNUMBER' | 'sub_tnumber_tnumber';
TCONTAINS_TCBUFFER_TCBUFFER: 'TCONTAINS_TCBUFFER_TCBUFFER' | 'tcontains_tcbuffer_tcbuffer';
TCONTAINS_TGEO_TGEO: 'TCONTAINS_TGEO_TGEO' | 'tcontains_tgeo_tgeo';
TCOVERS_TCBUFFER_TCBUFFER: 'TCOVERS_TCBUFFER_TCBUFFER' | 'tcovers_tcbuffer_tcbuffer';
TCOVERS_TGEO_TGEO: 'TCOVERS_TGEO_TGEO' | 'tcovers_tgeo_tgeo';
TDISTANCE_TCBUFFER_TCBUFFER: 'TDISTANCE_TCBUFFER_TCBUFFER' | 'tdistance_tcbuffer_tcbuffer';
TDISTANCE_TGEO_TGEO: 'TDISTANCE_TGEO_TGEO' | 'tdistance_tgeo_tgeo';
TDISTANCE_TNPOINT_TNPOINT: 'TDISTANCE_TNPOINT_TNPOINT' | 'tdistance_tnpoint_tnpoint';
TDISTANCE_TNUMBER_TNUMBER: 'TDISTANCE_TNUMBER_TNUMBER' | 'tdistance_tnumber_tnumber';
TDISTANCE_TPOSE_TPOSE: 'TDISTANCE_TPOSE_TPOSE' | 'tdistance_tpose_tpose';
CONTAINS_SPAN_SPAN: 'CONTAINS_SPAN_SPAN' | 'contains_span_span';
CONTAINED_SPAN_SPAN: 'CONTAINED_SPAN_SPAN' | 'contained_span_span';
ADJACENT_SPAN_SPAN: 'ADJACENT_SPAN_SPAN' | 'adjacent_span_span';
LEFT_SPAN_SPAN: 'LEFT_SPAN_SPAN' | 'left_span_span';
RIGHT_SPAN_SPAN: 'RIGHT_SPAN_SPAN' | 'right_span_span';
OVERLAPS_SPAN_SPAN: 'OVERLAPS_SPAN_SPAN' | 'overlaps_span_span';
OVERLEFT_SPAN_SPAN: 'OVERLEFT_SPAN_SPAN' | 'overleft_span_span';
OVERRIGHT_SPAN_SPAN: 'OVERRIGHT_SPAN_SPAN' | 'overright_span_span';
CONTAINS_SET_SET: 'CONTAINS_SET_SET' | 'contains_set_set';
CONTAINED_SET_SET: 'CONTAINED_SET_SET' | 'contained_set_set';
LEFT_SET_SET: 'LEFT_SET_SET' | 'left_set_set';
RIGHT_SET_SET: 'RIGHT_SET_SET' | 'right_set_set';
OVERLAPS_SET_SET: 'OVERLAPS_SET_SET' | 'overlaps_set_set';
OVERLEFT_SET_SET: 'OVERLEFT_SET_SET' | 'overleft_set_set';
OVERRIGHT_SET_SET: 'OVERRIGHT_SET_SET' | 'overright_set_set';
CONTAINS_SPANSET_SPAN: 'CONTAINS_SPANSET_SPAN' | 'contains_spanset_span';
CONTAINED_SPANSET_SPAN: 'CONTAINED_SPANSET_SPAN' | 'contained_spanset_span';
ADJACENT_SPANSET_SPAN: 'ADJACENT_SPANSET_SPAN' | 'adjacent_spanset_span';
LEFT_SPANSET_SPAN: 'LEFT_SPANSET_SPAN' | 'left_spanset_span';
RIGHT_SPANSET_SPAN: 'RIGHT_SPANSET_SPAN' | 'right_spanset_span';
OVERLAPS_SPANSET_SPAN: 'OVERLAPS_SPANSET_SPAN' | 'overlaps_spanset_span';
OVERLEFT_SPANSET_SPAN: 'OVERLEFT_SPANSET_SPAN' | 'overleft_spanset_span';
OVERRIGHT_SPANSET_SPAN: 'OVERRIGHT_SPANSET_SPAN' | 'overright_spanset_span';
CONTAINS_SPANSET_SPANSET: 'CONTAINS_SPANSET_SPANSET' | 'contains_spanset_spanset';
CONTAINED_SPANSET_SPANSET: 'CONTAINED_SPANSET_SPANSET' | 'contained_spanset_spanset';
ADJACENT_SPANSET_SPANSET: 'ADJACENT_SPANSET_SPANSET' | 'adjacent_spanset_spanset';
LEFT_SPANSET_SPANSET: 'LEFT_SPANSET_SPANSET' | 'left_spanset_spanset';
RIGHT_SPANSET_SPANSET: 'RIGHT_SPANSET_SPANSET' | 'right_spanset_spanset';
OVERLAPS_SPANSET_SPANSET: 'OVERLAPS_SPANSET_SPANSET' | 'overlaps_spanset_spanset';
OVERLEFT_SPANSET_SPANSET: 'OVERLEFT_SPANSET_SPANSET' | 'overleft_spanset_spanset';
OVERRIGHT_SPANSET_SPANSET: 'OVERRIGHT_SPANSET_SPANSET' | 'overright_spanset_spanset';
UNION_SPAN_SPAN: 'UNION_SPAN_SPAN' | 'union_span_span';
INTERSECTION_SPAN_SPAN: 'INTERSECTION_SPAN_SPAN' | 'intersection_span_span';
MINUS_SPAN_SPAN: 'MINUS_SPAN_SPAN' | 'minus_span_span';
UNION_SET_SET: 'UNION_SET_SET' | 'union_set_set';
INTERSECTION_SET_SET: 'INTERSECTION_SET_SET' | 'intersection_set_set';
MINUS_SET_SET: 'MINUS_SET_SET' | 'minus_set_set';
UNION_SPANSET_SPANSET: 'UNION_SPANSET_SPANSET' | 'union_spanset_spanset';
INTERSECTION_SPANSET_SPANSET: 'INTERSECTION_SPANSET_SPANSET' | 'intersection_spanset_spanset';
MINUS_SPANSET_SPANSET: 'MINUS_SPANSET_SPANSET' | 'minus_spanset_spanset';
UNION_SPAN_SPANSET: 'UNION_SPAN_SPANSET' | 'union_span_spanset';
INTERSECTION_SPAN_SPANSET: 'INTERSECTION_SPAN_SPANSET' | 'intersection_span_spanset';
MINUS_SPAN_SPANSET: 'MINUS_SPAN_SPANSET' | 'minus_span_spanset';
UNION_SPANSET_SPAN: 'UNION_SPANSET_SPAN' | 'union_spanset_span';
INTERSECTION_SPANSET_SPAN: 'INTERSECTION_SPANSET_SPAN' | 'intersection_spanset_span';
MINUS_SPANSET_SPAN: 'MINUS_SPANSET_SPAN' | 'minus_spanset_span';
ADJACENT_SPAN_FLOAT: 'ADJACENT_SPAN_FLOAT' | 'adjacent_span_float';
ADJACENT_SPAN_INT: 'ADJACENT_SPAN_INT' | 'adjacent_span_int';
ADJACENT_SPANSET_BIGINT: 'ADJACENT_SPANSET_BIGINT' | 'adjacent_spanset_bigint';
ADJACENT_SPANSET_FLOAT: 'ADJACENT_SPANSET_FLOAT' | 'adjacent_spanset_float';
ADJACENT_SPANSET_INT: 'ADJACENT_SPANSET_INT' | 'adjacent_spanset_int';
BEFORE_TBOX_TBOX: 'BEFORE_TBOX_TBOX' | 'before_tbox_tbox';
CONTAINED_BIGINT_SET: 'CONTAINED_BIGINT_SET' | 'contained_bigint_set';
CONTAINED_BIGINT_SPAN: 'CONTAINED_BIGINT_SPAN' | 'contained_bigint_span';
CONTAINED_BIGINT_SPANSET: 'CONTAINED_BIGINT_SPANSET' | 'contained_bigint_spanset';
CONTAINED_FLOAT_SET: 'CONTAINED_FLOAT_SET' | 'contained_float_set';
CONTAINED_FLOAT_SPAN: 'CONTAINED_FLOAT_SPAN' | 'contained_float_span';
CONTAINED_FLOAT_SPANSET: 'CONTAINED_FLOAT_SPANSET' | 'contained_float_spanset';
CONTAINED_INT_SET: 'CONTAINED_INT_SET' | 'contained_int_set';
CONTAINED_INT_SPAN: 'CONTAINED_INT_SPAN' | 'contained_int_span';
CONTAINED_INT_SPANSET: 'CONTAINED_INT_SPANSET' | 'contained_int_spanset';
CONTAINED_TBOX_TBOX: 'CONTAINED_TBOX_TBOX' | 'contained_tbox_tbox';
CONTAINS_SET_BIGINT: 'CONTAINS_SET_BIGINT' | 'contains_set_bigint';
CONTAINS_SET_FLOAT: 'CONTAINS_SET_FLOAT' | 'contains_set_float';
CONTAINS_SET_INT: 'CONTAINS_SET_INT' | 'contains_set_int';
CONTAINS_SPAN_BIGINT: 'CONTAINS_SPAN_BIGINT' | 'contains_span_bigint';
CONTAINS_SPAN_FLOAT: 'CONTAINS_SPAN_FLOAT' | 'contains_span_float';
CONTAINS_SPAN_INT: 'CONTAINS_SPAN_INT' | 'contains_span_int';
CONTAINS_SPANSET_BIGINT: 'CONTAINS_SPANSET_BIGINT' | 'contains_spanset_bigint';
CONTAINS_SPANSET_FLOAT: 'CONTAINS_SPANSET_FLOAT' | 'contains_spanset_float';
CONTAINS_SPANSET_INT: 'CONTAINS_SPANSET_INT' | 'contains_spanset_int';
CONTAINS_TBOX_TBOX: 'CONTAINS_TBOX_TBOX' | 'contains_tbox_tbox';
DISTANCE_SET_INT: 'DISTANCE_SET_INT' | 'distance_set_int';
DISTANCE_SPAN_INT: 'DISTANCE_SPAN_INT' | 'distance_span_int';
DISTANCE_SPANSET_INT: 'DISTANCE_SPANSET_INT' | 'distance_spanset_int';
INTERSECTION_FLOAT_SET: 'INTERSECTION_FLOAT_SET' | 'intersection_float_set';
INTERSECTION_INT_SET: 'INTERSECTION_INT_SET' | 'intersection_int_set';
INTERSECTION_SET_BIGINT: 'INTERSECTION_SET_BIGINT' | 'intersection_set_bigint';
INTERSECTION_SET_FLOAT: 'INTERSECTION_SET_FLOAT' | 'intersection_set_float';
INTERSECTION_SET_INT: 'INTERSECTION_SET_INT' | 'intersection_set_int';
INTERSECTION_SPAN_BIGINT: 'INTERSECTION_SPAN_BIGINT' | 'intersection_span_bigint';
INTERSECTION_SPAN_FLOAT: 'INTERSECTION_SPAN_FLOAT' | 'intersection_span_float';
INTERSECTION_SPAN_INT: 'INTERSECTION_SPAN_INT' | 'intersection_span_int';
INTERSECTION_SPANSET_BIGINT: 'INTERSECTION_SPANSET_BIGINT' | 'intersection_spanset_bigint';
INTERSECTION_SPANSET_FLOAT: 'INTERSECTION_SPANSET_FLOAT' | 'intersection_spanset_float';
INTERSECTION_SPANSET_INT: 'INTERSECTION_SPANSET_INT' | 'intersection_spanset_int';
INTERSECTION_STBOX_STBOX: 'INTERSECTION_STBOX_STBOX' | 'intersection_stbox_stbox';
INTERSECTION_TBOX_TBOX: 'INTERSECTION_TBOX_TBOX' | 'intersection_tbox_tbox';
LEFT_BIGINT_SET: 'LEFT_BIGINT_SET' | 'left_bigint_set';
LEFT_BIGINT_SPAN: 'LEFT_BIGINT_SPAN' | 'left_bigint_span';
LEFT_BIGINT_SPANSET: 'LEFT_BIGINT_SPANSET' | 'left_bigint_spanset';
LEFT_FLOAT_SET: 'LEFT_FLOAT_SET' | 'left_float_set';
LEFT_FLOAT_SPAN: 'LEFT_FLOAT_SPAN' | 'left_float_span';
LEFT_FLOAT_SPANSET: 'LEFT_FLOAT_SPANSET' | 'left_float_spanset';
LEFT_INT_SET: 'LEFT_INT_SET' | 'left_int_set';
LEFT_INT_SPAN: 'LEFT_INT_SPAN' | 'left_int_span';
LEFT_INT_SPANSET: 'LEFT_INT_SPANSET' | 'left_int_spanset';
LEFT_SET_BIGINT: 'LEFT_SET_BIGINT' | 'left_set_bigint';
LEFT_SET_FLOAT: 'LEFT_SET_FLOAT' | 'left_set_float';
LEFT_SET_INT: 'LEFT_SET_INT' | 'left_set_int';
LEFT_SPAN_BIGINT: 'LEFT_SPAN_BIGINT' | 'left_span_bigint';
LEFT_SPAN_FLOAT: 'LEFT_SPAN_FLOAT' | 'left_span_float';
LEFT_SPAN_INT: 'LEFT_SPAN_INT' | 'left_span_int';
LEFT_SPANSET_BIGINT: 'LEFT_SPANSET_BIGINT' | 'left_spanset_bigint';
LEFT_SPANSET_FLOAT: 'LEFT_SPANSET_FLOAT' | 'left_spanset_float';
LEFT_SPANSET_INT: 'LEFT_SPANSET_INT' | 'left_spanset_int';
LEFT_TBOX_TBOX: 'LEFT_TBOX_TBOX' | 'left_tbox_tbox';
MINUS_BIGINT_SET: 'MINUS_BIGINT_SET' | 'minus_bigint_set';
MINUS_BIGINT_SPAN: 'MINUS_BIGINT_SPAN' | 'minus_bigint_span';
MINUS_BIGINT_SPANSET: 'MINUS_BIGINT_SPANSET' | 'minus_bigint_spanset';
MINUS_FLOAT_SET: 'MINUS_FLOAT_SET' | 'minus_float_set';
MINUS_FLOAT_SPAN: 'MINUS_FLOAT_SPAN' | 'minus_float_span';
MINUS_FLOAT_SPANSET: 'MINUS_FLOAT_SPANSET' | 'minus_float_spanset';
MINUS_INT_SET: 'MINUS_INT_SET' | 'minus_int_set';
MINUS_INT_SPAN: 'MINUS_INT_SPAN' | 'minus_int_span';
MINUS_INT_SPANSET: 'MINUS_INT_SPANSET' | 'minus_int_spanset';
MINUS_SET_BIGINT: 'MINUS_SET_BIGINT' | 'minus_set_bigint';
MINUS_SET_FLOAT: 'MINUS_SET_FLOAT' | 'minus_set_float';
MINUS_SET_INT: 'MINUS_SET_INT' | 'minus_set_int';
MINUS_SPAN_BIGINT: 'MINUS_SPAN_BIGINT' | 'minus_span_bigint';
MINUS_SPAN_FLOAT: 'MINUS_SPAN_FLOAT' | 'minus_span_float';
MINUS_SPAN_INT: 'MINUS_SPAN_INT' | 'minus_span_int';
MINUS_SPANSET_BIGINT: 'MINUS_SPANSET_BIGINT' | 'minus_spanset_bigint';
MINUS_SPANSET_FLOAT: 'MINUS_SPANSET_FLOAT' | 'minus_spanset_float';
MINUS_SPANSET_INT: 'MINUS_SPANSET_INT' | 'minus_spanset_int';
NAD_TBOXINT_TBOXINT: 'NAD_TBOXINT_TBOXINT' | 'nad_tboxint_tboxint';
OVERAFTER_TBOX_TBOX: 'OVERAFTER_TBOX_TBOX' | 'overafter_tbox_tbox';
OVERBEFORE_TBOX_TBOX: 'OVERBEFORE_TBOX_TBOX' | 'overbefore_tbox_tbox';
OVERLAPS_TBOX_TBOX: 'OVERLAPS_TBOX_TBOX' | 'overlaps_tbox_tbox';
OVERLEFT_BIGINT_SET: 'OVERLEFT_BIGINT_SET' | 'overleft_bigint_set';
OVERLEFT_BIGINT_SPAN: 'OVERLEFT_BIGINT_SPAN' | 'overleft_bigint_span';
OVERLEFT_BIGINT_SPANSET: 'OVERLEFT_BIGINT_SPANSET' | 'overleft_bigint_spanset';
OVERLEFT_FLOAT_SET: 'OVERLEFT_FLOAT_SET' | 'overleft_float_set';
OVERLEFT_FLOAT_SPAN: 'OVERLEFT_FLOAT_SPAN' | 'overleft_float_span';
OVERLEFT_FLOAT_SPANSET: 'OVERLEFT_FLOAT_SPANSET' | 'overleft_float_spanset';
OVERLEFT_INT_SET: 'OVERLEFT_INT_SET' | 'overleft_int_set';
OVERLEFT_INT_SPAN: 'OVERLEFT_INT_SPAN' | 'overleft_int_span';
OVERLEFT_INT_SPANSET: 'OVERLEFT_INT_SPANSET' | 'overleft_int_spanset';
OVERLEFT_SET_BIGINT: 'OVERLEFT_SET_BIGINT' | 'overleft_set_bigint';
OVERLEFT_SET_FLOAT: 'OVERLEFT_SET_FLOAT' | 'overleft_set_float';
OVERLEFT_SET_INT: 'OVERLEFT_SET_INT' | 'overleft_set_int';
OVERLEFT_SPAN_BIGINT: 'OVERLEFT_SPAN_BIGINT' | 'overleft_span_bigint';
OVERLEFT_SPAN_FLOAT: 'OVERLEFT_SPAN_FLOAT' | 'overleft_span_float';
OVERLEFT_SPAN_INT: 'OVERLEFT_SPAN_INT' | 'overleft_span_int';
OVERLEFT_SPANSET_BIGINT: 'OVERLEFT_SPANSET_BIGINT' | 'overleft_spanset_bigint';
OVERLEFT_SPANSET_FLOAT: 'OVERLEFT_SPANSET_FLOAT' | 'overleft_spanset_float';
OVERLEFT_SPANSET_INT: 'OVERLEFT_SPANSET_INT' | 'overleft_spanset_int';
OVERLEFT_TBOX_TBOX: 'OVERLEFT_TBOX_TBOX' | 'overleft_tbox_tbox';
OVERRIGHT_BIGINT_SET: 'OVERRIGHT_BIGINT_SET' | 'overright_bigint_set';
OVERRIGHT_BIGINT_SPAN: 'OVERRIGHT_BIGINT_SPAN' | 'overright_bigint_span';
OVERRIGHT_BIGINT_SPANSET: 'OVERRIGHT_BIGINT_SPANSET' | 'overright_bigint_spanset';
OVERRIGHT_FLOAT_SET: 'OVERRIGHT_FLOAT_SET' | 'overright_float_set';
OVERRIGHT_FLOAT_SPAN: 'OVERRIGHT_FLOAT_SPAN' | 'overright_float_span';
OVERRIGHT_FLOAT_SPANSET: 'OVERRIGHT_FLOAT_SPANSET' | 'overright_float_spanset';
OVERRIGHT_INT_SET: 'OVERRIGHT_INT_SET' | 'overright_int_set';
OVERRIGHT_INT_SPAN: 'OVERRIGHT_INT_SPAN' | 'overright_int_span';
OVERRIGHT_INT_SPANSET: 'OVERRIGHT_INT_SPANSET' | 'overright_int_spanset';
OVERRIGHT_SET_BIGINT: 'OVERRIGHT_SET_BIGINT' | 'overright_set_bigint';
OVERRIGHT_SET_FLOAT: 'OVERRIGHT_SET_FLOAT' | 'overright_set_float';
OVERRIGHT_SET_INT: 'OVERRIGHT_SET_INT' | 'overright_set_int';
OVERRIGHT_SPAN_BIGINT: 'OVERRIGHT_SPAN_BIGINT' | 'overright_span_bigint';
OVERRIGHT_SPAN_FLOAT: 'OVERRIGHT_SPAN_FLOAT' | 'overright_span_float';
OVERRIGHT_SPAN_INT: 'OVERRIGHT_SPAN_INT' | 'overright_span_int';
OVERRIGHT_SPANSET_BIGINT: 'OVERRIGHT_SPANSET_BIGINT' | 'overright_spanset_bigint';
OVERRIGHT_SPANSET_FLOAT: 'OVERRIGHT_SPANSET_FLOAT' | 'overright_spanset_float';
OVERRIGHT_SPANSET_INT: 'OVERRIGHT_SPANSET_INT' | 'overright_spanset_int';
OVERRIGHT_TBOX_TBOX: 'OVERRIGHT_TBOX_TBOX' | 'overright_tbox_tbox';
RIGHT_BIGINT_SET: 'RIGHT_BIGINT_SET' | 'right_bigint_set';
RIGHT_BIGINT_SPAN: 'RIGHT_BIGINT_SPAN' | 'right_bigint_span';
RIGHT_BIGINT_SPANSET: 'RIGHT_BIGINT_SPANSET' | 'right_bigint_spanset';
RIGHT_FLOAT_SET: 'RIGHT_FLOAT_SET' | 'right_float_set';
RIGHT_FLOAT_SPAN: 'RIGHT_FLOAT_SPAN' | 'right_float_span';
RIGHT_FLOAT_SPANSET: 'RIGHT_FLOAT_SPANSET' | 'right_float_spanset';
RIGHT_INT_SET: 'RIGHT_INT_SET' | 'right_int_set';
RIGHT_INT_SPAN: 'RIGHT_INT_SPAN' | 'right_int_span';
RIGHT_INT_SPANSET: 'RIGHT_INT_SPANSET' | 'right_int_spanset';
RIGHT_SET_BIGINT: 'RIGHT_SET_BIGINT' | 'right_set_bigint';
RIGHT_SET_FLOAT: 'RIGHT_SET_FLOAT' | 'right_set_float';
RIGHT_SET_INT: 'RIGHT_SET_INT' | 'right_set_int';
RIGHT_SPAN_BIGINT: 'RIGHT_SPAN_BIGINT' | 'right_span_bigint';
RIGHT_SPAN_FLOAT: 'RIGHT_SPAN_FLOAT' | 'right_span_float';
RIGHT_SPAN_INT: 'RIGHT_SPAN_INT' | 'right_span_int';
RIGHT_SPANSET_BIGINT: 'RIGHT_SPANSET_BIGINT' | 'right_spanset_bigint';
RIGHT_SPANSET_FLOAT: 'RIGHT_SPANSET_FLOAT' | 'right_spanset_float';
RIGHT_SPANSET_INT: 'RIGHT_SPANSET_INT' | 'right_spanset_int';
RIGHT_TBOX_TBOX: 'RIGHT_TBOX_TBOX' | 'right_tbox_tbox';
SAME_TBOX_TBOX: 'SAME_TBOX_TBOX' | 'same_tbox_tbox';
TBOX_EQ: 'TBOX_EQ' | 'tbox_eq';
TBOX_GE: 'TBOX_GE' | 'tbox_ge';
TBOX_GT: 'TBOX_GT' | 'tbox_gt';
TBOX_LE: 'TBOX_LE' | 'tbox_le';
TBOX_LT: 'TBOX_LT' | 'tbox_lt';
TBOX_NE: 'TBOX_NE' | 'tbox_ne';
UNION_BIGINT_SET: 'UNION_BIGINT_SET' | 'union_bigint_set';
UNION_BIGINT_SPAN: 'UNION_BIGINT_SPAN' | 'union_bigint_span';
UNION_BIGINT_SPANSET: 'UNION_BIGINT_SPANSET' | 'union_bigint_spanset';
UNION_FLOAT_SET: 'UNION_FLOAT_SET' | 'union_float_set';
UNION_FLOAT_SPAN: 'UNION_FLOAT_SPAN' | 'union_float_span';
UNION_FLOAT_SPANSET: 'UNION_FLOAT_SPANSET' | 'union_float_spanset';
UNION_INT_SET: 'UNION_INT_SET' | 'union_int_set';
UNION_INT_SPAN: 'UNION_INT_SPAN' | 'union_int_span';
UNION_INT_SPANSET: 'UNION_INT_SPANSET' | 'union_int_spanset';
UNION_SET_BIGINT: 'UNION_SET_BIGINT' | 'union_set_bigint';
UNION_SET_FLOAT: 'UNION_SET_FLOAT' | 'union_set_float';
UNION_SET_INT: 'UNION_SET_INT' | 'union_set_int';
UNION_SPAN_BIGINT: 'UNION_SPAN_BIGINT' | 'union_span_bigint';
UNION_SPAN_FLOAT: 'UNION_SPAN_FLOAT' | 'union_span_float';
UNION_SPAN_INT: 'UNION_SPAN_INT' | 'union_span_int';
UNION_SPANSET_BIGINT: 'UNION_SPANSET_BIGINT' | 'union_spanset_bigint';
UNION_SPANSET_FLOAT: 'UNION_SPANSET_FLOAT' | 'union_spanset_float';
UNION_SPANSET_INT: 'UNION_SPANSET_INT' | 'union_spanset_int';
ADJACENT_SPAN_DATE: 'ADJACENT_SPAN_DATE' | 'adjacent_span_date';
ADJACENT_SPAN_SPANSET: 'ADJACENT_SPAN_SPANSET' | 'adjacent_span_spanset';
ADJACENT_SPAN_TIMESTAMPTZ: 'ADJACENT_SPAN_TIMESTAMPTZ' | 'adjacent_span_timestamptz';
ADJACENT_SPANSET_DATE: 'ADJACENT_SPANSET_DATE' | 'adjacent_spanset_date';
ADJACENT_SPANSET_TIMESTAMPTZ: 'ADJACENT_SPANSET_TIMESTAMPTZ' | 'adjacent_spanset_timestamptz';
AFTER_DATE_SPAN: 'AFTER_DATE_SPAN' | 'after_date_span';
AFTER_DATE_SPANSET: 'AFTER_DATE_SPANSET' | 'after_date_spanset';
AFTER_SET_DATE: 'AFTER_SET_DATE' | 'after_set_date';
AFTER_SET_TIMESTAMPTZ: 'AFTER_SET_TIMESTAMPTZ' | 'after_set_timestamptz';
AFTER_SPAN_DATE: 'AFTER_SPAN_DATE' | 'after_span_date';
AFTER_SPAN_TIMESTAMPTZ: 'AFTER_SPAN_TIMESTAMPTZ' | 'after_span_timestamptz';
AFTER_SPANSET_DATE: 'AFTER_SPANSET_DATE' | 'after_spanset_date';
AFTER_SPANSET_TIMESTAMPTZ: 'AFTER_SPANSET_TIMESTAMPTZ' | 'after_spanset_timestamptz';
AFTER_TIMESTAMPTZ_SET: 'AFTER_TIMESTAMPTZ_SET' | 'after_timestamptz_set';
AFTER_TIMESTAMPTZ_SPAN: 'AFTER_TIMESTAMPTZ_SPAN' | 'after_timestamptz_span';
AFTER_TIMESTAMPTZ_SPANSET: 'AFTER_TIMESTAMPTZ_SPANSET' | 'after_timestamptz_spanset';
BEFORE_DATE_SET: 'BEFORE_DATE_SET' | 'before_date_set';
BEFORE_DATE_SPAN: 'BEFORE_DATE_SPAN' | 'before_date_span';
BEFORE_DATE_SPANSET: 'BEFORE_DATE_SPANSET' | 'before_date_spanset';
BEFORE_SET_DATE: 'BEFORE_SET_DATE' | 'before_set_date';
BEFORE_SET_TIMESTAMPTZ: 'BEFORE_SET_TIMESTAMPTZ' | 'before_set_timestamptz';
BEFORE_SPAN_DATE: 'BEFORE_SPAN_DATE' | 'before_span_date';
BEFORE_SPAN_TIMESTAMPTZ: 'BEFORE_SPAN_TIMESTAMPTZ' | 'before_span_timestamptz';
BEFORE_SPANSET_DATE: 'BEFORE_SPANSET_DATE' | 'before_spanset_date';
BEFORE_SPANSET_TIMESTAMPTZ: 'BEFORE_SPANSET_TIMESTAMPTZ' | 'before_spanset_timestamptz';
BEFORE_TIMESTAMPTZ_SET: 'BEFORE_TIMESTAMPTZ_SET' | 'before_timestamptz_set';
BEFORE_TIMESTAMPTZ_SPAN: 'BEFORE_TIMESTAMPTZ_SPAN' | 'before_timestamptz_span';
BEFORE_TIMESTAMPTZ_SPANSET: 'BEFORE_TIMESTAMPTZ_SPANSET' | 'before_timestamptz_spanset';
CONTAINED_DATE_SET: 'CONTAINED_DATE_SET' | 'contained_date_set';
CONTAINED_DATE_SPAN: 'CONTAINED_DATE_SPAN' | 'contained_date_span';
CONTAINED_DATE_SPANSET: 'CONTAINED_DATE_SPANSET' | 'contained_date_spanset';
CONTAINED_SPAN_SPANSET: 'CONTAINED_SPAN_SPANSET' | 'contained_span_spanset';
CONTAINED_TIMESTAMPTZ_SET: 'CONTAINED_TIMESTAMPTZ_SET' | 'contained_timestamptz_set';
CONTAINED_TIMESTAMPTZ_SPAN: 'CONTAINED_TIMESTAMPTZ_SPAN' | 'contained_timestamptz_span';
CONTAINED_TIMESTAMPTZ_SPANSET: 'CONTAINED_TIMESTAMPTZ_SPANSET' | 'contained_timestamptz_spanset';
CONTAINS_SET_DATE: 'CONTAINS_SET_DATE' | 'contains_set_date';
CONTAINS_SET_TIMESTAMPTZ: 'CONTAINS_SET_TIMESTAMPTZ' | 'contains_set_timestamptz';
CONTAINS_SPAN_DATE: 'CONTAINS_SPAN_DATE' | 'contains_span_date';
CONTAINS_SPAN_SPANSET: 'CONTAINS_SPAN_SPANSET' | 'contains_span_spanset';
CONTAINS_SPAN_TIMESTAMPTZ: 'CONTAINS_SPAN_TIMESTAMPTZ' | 'contains_span_timestamptz';
CONTAINS_SPANSET_DATE: 'CONTAINS_SPANSET_DATE' | 'contains_spanset_date';
CONTAINS_SPANSET_TIMESTAMPTZ: 'CONTAINS_SPANSET_TIMESTAMPTZ' | 'contains_spanset_timestamptz';
LEFT_SPAN_SPANSET: 'LEFT_SPAN_SPANSET' | 'left_span_spanset';
OVERAFTER_DATE_SET: 'OVERAFTER_DATE_SET' | 'overafter_date_set';
OVERAFTER_DATE_SPAN: 'OVERAFTER_DATE_SPAN' | 'overafter_date_span';
OVERAFTER_DATE_SPANSET: 'OVERAFTER_DATE_SPANSET' | 'overafter_date_spanset';
OVERAFTER_SET_DATE: 'OVERAFTER_SET_DATE' | 'overafter_set_date';
OVERAFTER_SET_TIMESTAMPTZ: 'OVERAFTER_SET_TIMESTAMPTZ' | 'overafter_set_timestamptz';
OVERAFTER_SPAN_DATE: 'OVERAFTER_SPAN_DATE' | 'overafter_span_date';
OVERAFTER_SPAN_TIMESTAMPTZ: 'OVERAFTER_SPAN_TIMESTAMPTZ' | 'overafter_span_timestamptz';
OVERAFTER_SPANSET_DATE: 'OVERAFTER_SPANSET_DATE' | 'overafter_spanset_date';
OVERAFTER_SPANSET_TIMESTAMPTZ: 'OVERAFTER_SPANSET_TIMESTAMPTZ' | 'overafter_spanset_timestamptz';
OVERAFTER_TIMESTAMPTZ_SET: 'OVERAFTER_TIMESTAMPTZ_SET' | 'overafter_timestamptz_set';
OVERAFTER_TIMESTAMPTZ_SPAN: 'OVERAFTER_TIMESTAMPTZ_SPAN' | 'overafter_timestamptz_span';
OVERAFTER_TIMESTAMPTZ_SPANSET: 'OVERAFTER_TIMESTAMPTZ_SPANSET' | 'overafter_timestamptz_spanset';
OVERBEFORE_DATE_SET: 'OVERBEFORE_DATE_SET' | 'overbefore_date_set';
OVERBEFORE_DATE_SPAN: 'OVERBEFORE_DATE_SPAN' | 'overbefore_date_span';
OVERBEFORE_DATE_SPANSET: 'OVERBEFORE_DATE_SPANSET' | 'overbefore_date_spanset';
OVERBEFORE_SET_DATE: 'OVERBEFORE_SET_DATE' | 'overbefore_set_date';
OVERBEFORE_SET_TIMESTAMPTZ: 'OVERBEFORE_SET_TIMESTAMPTZ' | 'overbefore_set_timestamptz';
OVERBEFORE_SPAN_DATE: 'OVERBEFORE_SPAN_DATE' | 'overbefore_span_date';
OVERBEFORE_SPAN_TIMESTAMPTZ: 'OVERBEFORE_SPAN_TIMESTAMPTZ' | 'overbefore_span_timestamptz';
OVERBEFORE_SPANSET_DATE: 'OVERBEFORE_SPANSET_DATE' | 'overbefore_spanset_date';
OVERBEFORE_SPANSET_TIMESTAMPTZ: 'OVERBEFORE_SPANSET_TIMESTAMPTZ' | 'overbefore_spanset_timestamptz';
OVERBEFORE_TIMESTAMPTZ_SET: 'OVERBEFORE_TIMESTAMPTZ_SET' | 'overbefore_timestamptz_set';
OVERBEFORE_TIMESTAMPTZ_SPAN: 'OVERBEFORE_TIMESTAMPTZ_SPAN' | 'overbefore_timestamptz_span';
OVERBEFORE_TIMESTAMPTZ_SPANSET: 'OVERBEFORE_TIMESTAMPTZ_SPANSET' | 'overbefore_timestamptz_spanset';
OVERLAPS_SPAN_SPANSET: 'OVERLAPS_SPAN_SPANSET' | 'overlaps_span_spanset';
OVERLEFT_SPAN_SPANSET: 'OVERLEFT_SPAN_SPANSET' | 'overleft_span_spanset';
OVERRIGHT_SPAN_SPANSET: 'OVERRIGHT_SPAN_SPANSET' | 'overright_span_spanset';
RIGHT_SPAN_SPANSET: 'RIGHT_SPAN_SPANSET' | 'right_span_spanset';
INTSPAN_LOWER: 'INTSPAN_LOWER' | 'intspan_lower';
INTSPAN_UPPER: 'INTSPAN_UPPER' | 'intspan_upper';
INTSPAN_WIDTH: 'INTSPAN_WIDTH' | 'intspan_width';
BIGINTSPAN_LOWER: 'BIGINTSPAN_LOWER' | 'bigintspan_lower';
BIGINTSPAN_UPPER: 'BIGINTSPAN_UPPER' | 'bigintspan_upper';
BIGINTSPAN_WIDTH: 'BIGINTSPAN_WIDTH' | 'bigintspan_width';
FLOATSPAN_LOWER: 'FLOATSPAN_LOWER' | 'floatspan_lower';
FLOATSPAN_UPPER: 'FLOATSPAN_UPPER' | 'floatspan_upper';
FLOATSPAN_WIDTH: 'FLOATSPAN_WIDTH' | 'floatspan_width';
DATESPAN_LOWER: 'DATESPAN_LOWER' | 'datespan_lower';
DATESPAN_UPPER: 'DATESPAN_UPPER' | 'datespan_upper';
TSTZSPAN_LOWER: 'TSTZSPAN_LOWER' | 'tstzspan_lower';
TSTZSPAN_UPPER: 'TSTZSPAN_UPPER' | 'tstzspan_upper';
INTSPANSET_LOWER: 'INTSPANSET_LOWER' | 'intspanset_lower';
INTSPANSET_UPPER: 'INTSPANSET_UPPER' | 'intspanset_upper';
BIGINTSPANSET_LOWER: 'BIGINTSPANSET_LOWER' | 'bigintspanset_lower';
BIGINTSPANSET_UPPER: 'BIGINTSPANSET_UPPER' | 'bigintspanset_upper';
FLOATSPANSET_LOWER: 'FLOATSPANSET_LOWER' | 'floatspanset_lower';
FLOATSPANSET_UPPER: 'FLOATSPANSET_UPPER' | 'floatspanset_upper';
TSTZSPANSET_LOWER: 'TSTZSPANSET_LOWER' | 'tstzspanset_lower';
TSTZSPANSET_UPPER: 'TSTZSPANSET_UPPER' | 'tstzspanset_upper';
INTSET_START_VALUE: 'INTSET_START_VALUE' | 'intset_start_value';
INTSET_END_VALUE: 'INTSET_END_VALUE' | 'intset_end_value';
BIGINTSET_START_VALUE: 'BIGINTSET_START_VALUE' | 'bigintset_start_value';
BIGINTSET_END_VALUE: 'BIGINTSET_END_VALUE' | 'bigintset_end_value';
FLOATSET_START_VALUE: 'FLOATSET_START_VALUE' | 'floatset_start_value';
FLOATSET_END_VALUE: 'FLOATSET_END_VALUE' | 'floatset_end_value';
DATESET_START_VALUE: 'DATESET_START_VALUE' | 'dateset_start_value';
DATESET_END_VALUE: 'DATESET_END_VALUE' | 'dateset_end_value';
TSTZSET_START_VALUE: 'TSTZSET_START_VALUE' | 'tstzset_start_value';
TSTZSET_END_VALUE: 'TSTZSET_END_VALUE' | 'tstzset_end_value';
SPAN_LOWER_INC: 'SPAN_LOWER_INC' | 'span_lower_inc';
SPAN_UPPER_INC: 'SPAN_UPPER_INC' | 'span_upper_inc';
SPANSET_LOWER_INC: 'SPANSET_LOWER_INC' | 'spanset_lower_inc';
SPANSET_UPPER_INC: 'SPANSET_UPPER_INC' | 'spanset_upper_inc';
SET_NUM_VALUES: 'SET_NUM_VALUES' | 'set_num_values';
SPANSET_NUM_SPANS: 'SPANSET_NUM_SPANS' | 'spanset_num_spans';
/* END CODEGEN LEXER TOKENS */
/* BEGIN CODEGEN AGGREGATION LEXER TOKENS */
TEMPORAL_NUM_INSTANTS: 'TEMPORAL_NUM_INSTANTS' | 'temporal_num_instants';
TEMPORAL_NUM_SEQUENCES: 'TEMPORAL_NUM_SEQUENCES' | 'temporal_num_sequences';
TEMPORAL_NUM_TIMESTAMPS: 'TEMPORAL_NUM_TIMESTAMPS' | 'temporal_num_timestamps';
TEMPORAL_TFLOAT_START_VALUE: 'TEMPORAL_TFLOAT_START_VALUE' | 'temporal_tfloat_start_value';
TEMPORAL_TFLOAT_END_VALUE: 'TEMPORAL_TFLOAT_END_VALUE' | 'temporal_tfloat_end_value';
TEMPORAL_TFLOAT_MIN_VALUE: 'TEMPORAL_TFLOAT_MIN_VALUE' | 'temporal_tfloat_min_value';
TEMPORAL_TFLOAT_MAX_VALUE: 'TEMPORAL_TFLOAT_MAX_VALUE' | 'temporal_tfloat_max_value';
TEMPORAL_TNUMBER_INTEGRAL: 'TEMPORAL_TNUMBER_INTEGRAL' | 'temporal_tnumber_integral';
TEMPORAL_TINT_START_VALUE: 'TEMPORAL_TINT_START_VALUE' | 'temporal_tint_start_value';
TEMPORAL_TINT_END_VALUE: 'TEMPORAL_TINT_END_VALUE' | 'temporal_tint_end_value';
TEMPORAL_TINT_MIN_VALUE: 'TEMPORAL_TINT_MIN_VALUE' | 'temporal_tint_min_value';
TEMPORAL_TINT_MAX_VALUE: 'TEMPORAL_TINT_MAX_VALUE' | 'temporal_tint_max_value';
TEMPORAL_TFLOAT_AVG_VALUE: 'TEMPORAL_TFLOAT_AVG_VALUE' | 'temporal_tfloat_avg_value';
TEMPORAL_TNUMBER_TWAVG: 'TEMPORAL_TNUMBER_TWAVG' | 'temporal_tnumber_twavg';
TEMPORAL_TINT_AVG_VALUE: 'TEMPORAL_TINT_AVG_VALUE' | 'temporal_tint_avg_value';
TEMPORAL_START_TIMESTAMP: 'TEMPORAL_START_TIMESTAMP' | 'temporal_start_timestamp';
TEMPORAL_END_TIMESTAMP: 'TEMPORAL_END_TIMESTAMP' | 'temporal_end_timestamp';
TEMPORAL_LOWER_INC: 'TEMPORAL_LOWER_INC' | 'temporal_lower_inc';
TEMPORAL_UPPER_INC: 'TEMPORAL_UPPER_INC' | 'temporal_upper_inc';
TEMPORAL_TPOINT_IS_SIMPLE: 'TEMPORAL_TPOINT_IS_SIMPLE' | 'temporal_tpoint_is_simple';
TSPATIAL_EXTENT: 'TSPATIAL_EXTENT' | 'tspatial_extent';
TNUMBER_EXTENT: 'TNUMBER_EXTENT' | 'tnumber_extent';
FLOAT_EXTENT: 'FLOAT_EXTENT' | 'float_extent';
INT_EXTENT: 'INT_EXTENT' | 'int_extent';
BIGINT_EXTENT: 'BIGINT_EXTENT' | 'bigint_extent';
TIMESTAMPTZ_EXTENT: 'TIMESTAMPTZ_EXTENT' | 'timestamptz_extent';
FLOAT_UNION: 'FLOAT_UNION' | 'float_union';
INT_UNION: 'INT_UNION' | 'int_union';
BIGINT_UNION: 'BIGINT_UNION' | 'bigint_union';
TIMESTAMPTZ_UNION: 'TIMESTAMPTZ_UNION' | 'timestamptz_union';
TRAJECTORY_WKB: 'TRAJECTORY_WKB' | 'trajectory_wkb';
TLENGTH_EXP: 'TLENGTH_EXP' | 'tlength_exp';
TGEO_CENTROID_EXP: 'TGEO_CENTROID_EXP' | 'tgeo_centroid_exp';
TPOINT_AZIMUTH_EXP: 'TPOINT_AZIMUTH_EXP' | 'tpoint_azimuth_exp';
TPOINT_ANGULAR_DIFFERENCE_EXP: 'TPOINT_ANGULAR_DIFFERENCE_EXP' | 'tpoint_angular_difference_exp';
TGEOMPOINT_TO_TGEOMETRY_EXP: 'TGEOMPOINT_TO_TGEOMETRY_EXP' | 'tgeompoint_to_tgeometry_exp';
TEMPORAL_COPY_EXP: 'TEMPORAL_COPY_EXP' | 'temporal_copy_exp';
TNUMBER_ABS_EXP: 'TNUMBER_ABS_EXP' | 'tnumber_abs_exp';
TNUMBER_DELTA_VALUE_EXP: 'TNUMBER_DELTA_VALUE_EXP' | 'tnumber_delta_value_exp';
TNUMBER_ANGULAR_DIFFERENCE_EXP: 'TNUMBER_ANGULAR_DIFFERENCE_EXP' | 'tnumber_angular_difference_exp';
TEMPORAL_DERIVATIVE_EXP: 'TEMPORAL_DERIVATIVE_EXP' | 'temporal_derivative_exp';
TEMPORAL_AT_MAX_EXP: 'TEMPORAL_AT_MAX_EXP' | 'temporal_at_max_exp';
TEMPORAL_AT_MIN_EXP: 'TEMPORAL_AT_MIN_EXP' | 'temporal_at_min_exp';
TEMPORAL_MINUS_MAX_EXP: 'TEMPORAL_MINUS_MAX_EXP' | 'temporal_minus_max_exp';
TEMPORAL_MINUS_MIN_EXP: 'TEMPORAL_MINUS_MIN_EXP' | 'temporal_minus_min_exp';
TNPOINT_CUMULATIVE_LENGTH_EXP: 'TNPOINT_CUMULATIVE_LENGTH_EXP' | 'tnpoint_cumulative_length_exp';
TNPOINT_SPEED_EXP: 'TNPOINT_SPEED_EXP' | 'tnpoint_speed_exp';
TNPOINT_TO_TGEOMPOINT_EXP: 'TNPOINT_TO_TGEOMPOINT_EXP' | 'tnpoint_to_tgeompoint_exp';
TPOINT_CUMULATIVE_LENGTH_EXP: 'TPOINT_CUMULATIVE_LENGTH_EXP' | 'tpoint_cumulative_length_exp';
TPOINT_SPEED_EXP: 'TPOINT_SPEED_EXP' | 'tpoint_speed_exp';
TPOINT_GET_X_EXP: 'TPOINT_GET_X_EXP' | 'tpoint_get_x_exp';
TPOINT_GET_Y_EXP: 'TPOINT_GET_Y_EXP' | 'tpoint_get_y_exp';
TNUMBER_TREND_EXP: 'TNUMBER_TREND_EXP' | 'tnumber_trend_exp';
TGEO_START_VALUE_EXP: 'TGEO_START_VALUE_EXP' | 'tgeo_start_value_exp';
TGEO_END_VALUE_EXP: 'TGEO_END_VALUE_EXP' | 'tgeo_end_value_exp';
TGEO_CONVEX_HULL_EXP: 'TGEO_CONVEX_HULL_EXP' | 'tgeo_convex_hull_exp';
TPOINT_TWCENTROID_EXP: 'TPOINT_TWCENTROID_EXP' | 'tpoint_twcentroid_exp';
/* END CODEGEN AGGREGATION LEXER TOKENS */
WATERMARK: 'WATERMARK' | 'watermark';
OFFSET: 'OFFSET' | 'offset';
LOCALHOST: 'LOCALHOST' | 'localhost';
CSV_FORMAT : 'CSV_FORMAT';
AT_MOST_ONCE : 'AT_MOST_ONCE';
AT_LEAST_ONCE : 'AT_LEAST_ONCE';
JSON: 'JSON';
TEXT: 'TEXT';
///--NebulaSQL-KEYWORD-LIST-END
///****************************
/// End of the keywords list
///****************************



BOOLEAN_VALUE: 'true' | 'false';
EQ  : '=' | '==';
NSEQ: '<=>';
NEQ : '<>';
NEQJ: '!=';
LT  : '<';
LTE : '<=' | '!>';
GT  : '>';
GTE : '>=' | '!<';

PLUS: '+';
MINUS: '-';
ASTERISK: '*';
SLASH: '/';
PERCENT: '%';
TILDE: '~';
AMPERSAND: '&';
PIPE: '|';
CONCAT_PIPE: '||';
HAT: '^';

STRING
    : '\'' ( ~('\''|'\\') | ('\\' .) )* '\''
    | '"' ( ~('"'|'\\') | ('\\' .) )* '"'
    ;

INTEGER_VALUE
    : DIGIT+
    ;

FLOAT_LITERAL
    : DIGIT+ EXPONENT?
    | DECIMAL_DIGITS EXPONENT? {isValidDecimal()}?
    ;


fragment DECIMAL_DIGITS
    : DIGIT+ '.' DIGIT*
    | '.' DIGIT+
    ;

fragment EXPONENT
    : 'E' [+-]? DIGIT+
    ;

fragment DIGIT
    : [0-9]
    ;

fragment LETTER
    : ('a'..'z'|'A'..'Z'|'_')
    ;

WS
    : [ \r\n\t]+ -> channel(HIDDEN)
    ;


SINKS: 'SINKS';
SOURCES: 'SOURCES' | 'sources';
QUERIES: 'QUERIES' | 'queries';


DATA_TYPE: INTEGER_SIGNED_TYPE | INTEGER_UNSIGNED_TYPE | FLOATING_POINT_TYPE | CHAR_TYPE | VARSIZED_TYPE | BOOLEAN_TYPE;

INTEGER_UNSIGNED_TYPE: UNSIGNED_TYPE_QUALIFIER INTEGER_BASES_TYPES | 'UINT8' | 'UINT16' | 'UINT32' | 'UINT64';
INTEGER_SIGNED_TYPE: INTEGER_BASES_TYPES | 'INT64' | 'INT32' | 'INT16' | 'INT8';
INTEGER_BASES_TYPES: TINY_INT_TYPE | SMALL_INT_TYPE | NORMAL_INT_TYPE | BIG_INT_TYPE;
TINY_INT_TYPE: 'TINYINT';
SMALL_INT_TYPE: 'SMALLINT';
NORMAL_INT_TYPE: 'INT' | 'INTEGER';
BIG_INT_TYPE: 'BIGINT';
FLOATING_POINT_TYPE: 'FLOAT32' | 'FLOAT64';
CHAR_TYPE: 'CHAR';
VARSIZED_TYPE: 'VARSIZED';
BOOLEAN_TYPE: 'BOOLEAN';

UNSIGNED_TYPE_QUALIFIER: 'UNSIGNED ';



SHOW : 'SHOW';
FORMAT : 'FORMAT';
CREATE : 'CREATE';
SOURCE : 'SOURCE';
LOGICAL: 'LOGICAL';
PHYSICAL: 'PHYSICAL';
SINK : 'SINK';

//Make sure that you add lexer rules for keywords before the identifier rule,
//otherwise it will take priority and your grammars will not work

SIMPLE_COMMENT
    : '--' ('\\\n' | ~[\r\n])* '\r'? '\n'? -> channel(HIDDEN)
    ;

BRACKETED_COMMENT
    : '/*' {!isHint()}? (BRACKETED_COMMENT|.)*? '*/' -> channel(HIDDEN)
    ;

IDENTIFIER
    : LETTER (LETTER | DIGIT | '_')*
    ;

/// Catch-all for anything we can't recognize.
/// We use this to be able to ignore and recover all the text
/// when splitting statements with DelimiterLexer
UNRECOGNIZED
    : .
    ;
