/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Functions/PhysicalFunction.hpp>
#include <Nautilus/DataTypes/VarVal.hpp>
#include <Nautilus/Interface/Record.hpp>
#include <vector>

namespace NES {

/**
 * @brief Physical operator for `box3d_make`.
 *
 * box3d_make (BOX3D *) - a PostGIS BOX3D from its bounds (xmin,xmax,ymin,ymax,zmin,zmax,srid).
 *
 * Generated by tools/codegen/codegen_nebula.py.
 */
class Box3dMakePhysicalFunction : public PhysicalFunctionConcept {
public:
    Box3dMakePhysicalFunction(PhysicalFunction valueFunction,
                                                          PhysicalFunction arg0Function,
                                                          PhysicalFunction arg1Function,
                                                          PhysicalFunction arg2Function,
                                                          PhysicalFunction arg3Function,
                                                          PhysicalFunction arg4Function,
                                                          PhysicalFunction arg5Function);

    VarVal execute(const Record& record, ArenaRef& arena) const override;

private:
    std::vector<PhysicalFunction> parameterFunctions;
};

} // namespace NES
