/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Functions/PhysicalFunction.hpp>
#include <Nautilus/DataTypes/VarVal.hpp>
#include <Nautilus/Interface/Record.hpp>
#include <vector>

namespace NES {

/**
 * @brief Physical operator for `div_tbigint_bigint`.
 *
 * Per-event div_tbigint_bigint: divides a single-instant tbigint value by a constant int64.
 *
 * Generated by tools/codegen/codegen_nebula.py.
 */
class DivTbigintBigintPhysicalFunction : public PhysicalFunctionConcept {
public:
    DivTbigintBigintPhysicalFunction(PhysicalFunction valueFunction,
                                     PhysicalFunction tsFunction,
                                     PhysicalFunction divisorFunction);

    VarVal execute(const Record& record, ArenaRef& arena) const override;

private:
    std::vector<PhysicalFunction> parameterFunctions;
};

} // namespace NES
