/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Functions/PhysicalFunction.hpp>
#include <Nautilus/DataTypes/VarVal.hpp>
#include <Nautilus/Interface/Record.hpp>
#include <vector>

namespace NES {

/**
 * @brief Physical operator for `({Span* _sp=floatspan_make(lower,upper,lower_inc!=0.0,upper_inc!=0.0);if(!_sp)return 0u;char* _out=floatspan_out(_sp,-1);free(_sp);_out;})`.
 *
 * Construct a float span from bounds and inclusivity flags.
 *
 * Generated by tools/codegen/codegen_nebula.py.
 */
class FloatspanMakePhysicalFunction : public PhysicalFunctionConcept {
public:
    FloatspanMakePhysicalFunction(PhysicalFunction lowerFunction,
                                                          PhysicalFunction upperFunction,
                                                          PhysicalFunction lower_incFunction,
                                                          PhysicalFunction upper_incFunction);

    VarVal execute(const Record& record, ArenaRef& arena) const override;

private:
    std::vector<PhysicalFunction> parameterFunctions;
};

} // namespace NES
