/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Functions/PhysicalFunction.hpp>
#include <Nautilus/DataTypes/VarVal.hpp>
#include <Nautilus/Interface/Record.hpp>
#include <vector>

namespace NES {

/**
 * @brief Physical operator for `({std::string _s(wktPtr,wktSize),_ps(paramsPtr,paramsSize);GSERIALIZED* _gs=geom_in(_s.c_str(),-1);if(!_gs)return 0u;GSERIALIZED* _res=geom_buffer(_gs,size,_ps.c_str());free(_gs);_res;})`.
 *
 * Compute the buffer zone around a geometry.
 *
 * Generated by tools/codegen/codegen_nebula.py.
 */
class GeomBufferPhysicalFunction : public PhysicalFunctionConcept {
public:
    GeomBufferPhysicalFunction(PhysicalFunction wktFunction,
                                                          PhysicalFunction sizeFunction,
                                                          PhysicalFunction paramsFunction);

    VarVal execute(const Record& record, ArenaRef& arena) const override;

private:
    std::vector<PhysicalFunction> parameterFunctions;
};

} // namespace NES
