/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Functions/PhysicalFunction.hpp>
#include <Nautilus/DataTypes/VarVal.hpp>
#include <Nautilus/Interface/Record.hpp>
#include <vector>

namespace NES {

/**
 * @brief Physical operator for `({std::string _s(wktPtr,wktSize),_ps(pipelinePtr,pipelineSize);GSERIALIZED* _gs=geom_in(_s.c_str(),-1);if(!_gs)return 0u;GSERIALIZED* _res=geo_transform_pipeline(_gs,const_cast<char*>(_ps.c_str()),(int32_t)srid_to,(bool)is_forward);free(_gs);_res;})`.
 *
 * Transform geometry through a coordinate pipeline.
 *
 * Generated by tools/codegen/codegen_nebula.py.
 */
class GeoTransformPipelinePhysicalFunction : public PhysicalFunctionConcept {
public:
    GeoTransformPipelinePhysicalFunction(PhysicalFunction wktFunction,
                                                          PhysicalFunction pipelineFunction,
                                                          PhysicalFunction srid_toFunction,
                                                          PhysicalFunction is_forwardFunction);

    VarVal execute(const Record& record, ArenaRef& arena) const override;

private:
    std::vector<PhysicalFunction> parameterFunctions;
};

} // namespace NES
