/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Functions/PhysicalFunction.hpp>
#include <Nautilus/DataTypes/VarVal.hpp>
#include <Nautilus/Interface/Record.hpp>
#include <vector>

namespace NES {

/**
 * @brief Physical operator for `({std::string _wkt=fmt::format("SRID=4326;POINT({} {})",lon,lat);GSERIALIZED* _gs=geom_in(_wkt.c_str(),-1);if(!_gs)return 0u;H3Index _cell=h3_gs_point_to_cell(_gs,(int32_t)res);free(_gs);_cell;})`.
 *
 * Map (lon,lat) point to H3 cell at given resolution.
 *
 * Generated by tools/codegen/codegen_nebula.py.
 */
class H3GsPointToCellPhysicalFunction : public PhysicalFunctionConcept {
public:
    H3GsPointToCellPhysicalFunction(PhysicalFunction lonFunction,
                                                          PhysicalFunction latFunction,
                                                          PhysicalFunction resFunction);

    VarVal execute(const Record& record, ArenaRef& arena) const override;

private:
    std::vector<PhysicalFunction> parameterFunctions;
};

} // namespace NES
