/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Functions/PhysicalFunction.hpp>
#include <Nautilus/DataTypes/VarVal.hpp>
#include <Nautilus/Interface/Record.hpp>
#include <vector>

namespace NES {

/**
 * @brief Physical operator for `({std::string _sj(jsonPtr,jsonSize),_sk(keyPtr,keySize);text* _js=json_in(_sj.c_str());if(!_js)return 0u;text* _key=cstring_to_text(_sk.c_str());text* _res=json_object_field_text(_js,_key);free(_js);free(_key);_res;})`.
 *
 * Text value of a JSON object field by key.
 *
 * Generated by tools/codegen/codegen_nebula.py.
 */
class JsonObjectFieldTextPhysicalFunction : public PhysicalFunctionConcept {
public:
    JsonObjectFieldTextPhysicalFunction(PhysicalFunction jsonFunction,
                                                          PhysicalFunction keyFunction);

    VarVal execute(const Record& record, ArenaRef& arena) const override;

private:
    std::vector<PhysicalFunction> parameterFunctions;
};

} // namespace NES
