/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Functions/PhysicalFunction.hpp>
#include <Nautilus/DataTypes/VarVal.hpp>
#include <Nautilus/Interface/Record.hpp>
#include <vector>

namespace NES {

/**
 * @brief Physical operator for `mul_tint_int`.
 *
 * Per-event mul_tint_int: multiplies a single-instant tint value by a constant integer.
 *
 * Generated by tools/codegen/codegen_nebula.py.
 */
class MulTintIntPhysicalFunction : public PhysicalFunctionConcept {
public:
    MulTintIntPhysicalFunction(PhysicalFunction valueFunction,
                               PhysicalFunction tsFunction,
                               PhysicalFunction multiplierFunction);

    VarVal execute(const Record& record, ArenaRef& arena) const override;

private:
    std::vector<PhysicalFunction> parameterFunctions;
};

} // namespace NES
