/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Functions/PhysicalFunction.hpp>
#include <Nautilus/DataTypes/VarVal.hpp>
#include <Nautilus/Interface/Record.hpp>
#include <vector>

namespace NES {

/**
 * @brief Physical operator for `nad_tgeo_stbox`.
 *
 * Per-event nad_tgeo_stbox: single-instant tgeompoint against a stbox literal -> double.
 *
 * Generated by tools/codegen/codegen_nebula.py.
 */
class NadTgeoStboxPhysicalFunction : public PhysicalFunctionConcept {
public:
    NadTgeoStboxPhysicalFunction(PhysicalFunction lonFunction,
                                                          PhysicalFunction latFunction,
                                                          PhysicalFunction tsFunction,
                                                          PhysicalFunction arg0Function);

    VarVal execute(const Record& record, ArenaRef& arena) const override;

private:
    std::vector<PhysicalFunction> parameterFunctions;
};

} // namespace NES
