/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Functions/PhysicalFunction.hpp>
#include <Nautilus/DataTypes/VarVal.hpp>
#include <Nautilus/Interface/Record.hpp>
#include <vector>

namespace NES {

/**
 * @brief Physical operator for `stbox_make`.
 *
 * stbox_make (STBox *) - an STBox from hasx/hasz/geodetic, srid, the six bounds (xmin,xmax,ymin,ymax,zmin,zmax) and a time span.
 *
 * Generated by tools/codegen/codegen_nebula.py.
 */
class StboxMakePhysicalFunction : public PhysicalFunctionConcept {
public:
    StboxMakePhysicalFunction(PhysicalFunction valueFunction,
                                                          PhysicalFunction arg0Function,
                                                          PhysicalFunction arg1Function,
                                                          PhysicalFunction arg2Function,
                                                          PhysicalFunction arg3Function,
                                                          PhysicalFunction arg4Function,
                                                          PhysicalFunction arg5Function,
                                                          PhysicalFunction arg6Function,
                                                          PhysicalFunction arg7Function,
                                                          PhysicalFunction arg8Function,
                                                          PhysicalFunction arg9Function);

    VarVal execute(const Record& record, ArenaRef& arena) const override;

private:
    std::vector<PhysicalFunction> parameterFunctions;
};

} // namespace NES
