/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Functions/PhysicalFunction.hpp>
#include <Nautilus/DataTypes/VarVal.hpp>
#include <Nautilus/Interface/Record.hpp>
#include <vector>

namespace NES {

/**
 * @brief Physical operator for `tdistance_trgeometry_trgeometry`.
 *
 * tdistance_trgeometry_trgeometry (Temporal *) — two trgeometry instants -> tfloat_out.
 *
 * Generated by tools/codegen/codegen_nebula.py.
 */
class TdistanceTrgeometryTrgeometryPhysicalFunction : public PhysicalFunctionConcept {
public:
    TdistanceTrgeometryTrgeometryPhysicalFunction(PhysicalFunction xFunction,
                                                          PhysicalFunction yFunction,
                                                          PhysicalFunction thetaFunction,
                                                          PhysicalFunction tsFunction,
                                                          PhysicalFunction x2Function,
                                                          PhysicalFunction y2Function,
                                                          PhysicalFunction theta2Function,
                                                          PhysicalFunction ts2Function);

    VarVal execute(const Record& record, ArenaRef& arena) const override;

private:
    std::vector<PhysicalFunction> parameterFunctions;
};

} // namespace NES
