/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Functions/LogicalFunction.hpp>
#include <string_view>
#include <utility>
#include <vector>

namespace NES {

/**
 * @brief Per-event always_eq_tbigint_tfloat: tests if two single-instant tbigint values are always equal.
 *
 * Generated by tools/codegen/codegen_nebula.py from the MEOS function
 * `always_eq_tbigint_tfloat`. Takes (value1:FLOAT64, value2:FLOAT64, ts:UINT64),
 * constructs two single-instant temporals, applies the comparison, and returns FLOAT64 (0.0/1.0).
 */
class AlwaysEqTbigintTfloatLogicalFunction : public LogicalFunctionConcept {
public:
    static constexpr std::string_view NAME = "AlwaysEqTbigintTfloat";

    AlwaysEqTbigintTfloatLogicalFunction(LogicalFunction value1,
                                      LogicalFunction value2,
                                      LogicalFunction ts);

    DataType getDataType() const override;
    LogicalFunction withDataType(const DataType& dataType) const override;
    std::vector<LogicalFunction> getChildren() const override;
    LogicalFunction withChildren(const std::vector<LogicalFunction>& children) const override;
    std::string_view getType() const override;
    bool operator==(const LogicalFunctionConcept& rhs) const override;
    std::string explain(ExplainVerbosity verbosity) const override;
    LogicalFunction withInferredDataType(const Schema& schema) const override;
    SerializableFunction serialize() const override;

private:
    DataType dataType;
    std::vector<LogicalFunction> parameters;
};

} // namespace NES
