/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Functions/LogicalFunction.hpp>
#include <string_view>
#include <utility>
#include <vector>

namespace NES {

/**
 * @brief Test DE-9IM relation pattern between two geometries.
 *
 * Generated by tools/codegen/codegen_nebula.py from the MEOS function
 * `({std::string _s1(wkt1Ptr,wkt1Size),_s2(wkt2Ptr,wkt2Size),_sp(patternPtr,patternSize);GSERIALIZED* _gs1=geom_in(_s1.c_str(),-1);if(!_gs1)return 0.0;GSERIALIZED* _gs2=geom_in(_s2.c_str(),-1);if(!_gs2){free(_gs1);return 0.0;}bool _r=geom_relate_pattern(_gs1,_gs2,const_cast<char*>(_sp.c_str()));free(_gs1);free(_gs2);_r?1.0:0.0;})`. Per-event scalar operator following the
 * TemporalEDWithinGeometry pattern.
 */
class GeomRelatePatternLogicalFunction : public LogicalFunctionConcept {
public:
    static constexpr std::string_view NAME = "GeomRelatePattern";

    GeomRelatePatternLogicalFunction(LogicalFunction wkt1,
                                          LogicalFunction wkt2,
                                          LogicalFunction pattern);

    DataType getDataType() const override;
    LogicalFunction withDataType(const DataType& dataType) const override;
    std::vector<LogicalFunction> getChildren() const override;
    LogicalFunction withChildren(const std::vector<LogicalFunction>& children) const override;
    std::string_view getType() const override;
    bool operator==(const LogicalFunctionConcept& rhs) const override;
    std::string explain(ExplainVerbosity verbosity) const override;
    LogicalFunction withInferredDataType(const Schema& schema) const override;
    SerializableFunction serialize() const override;

private:
    DataType dataType;
    std::vector<LogicalFunction> parameters;
};

} // namespace NES
