/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Functions/LogicalFunction.hpp>
#include <string_view>
#include <utility>
#include <vector>

namespace NES {

/**
 * @brief Text value of a JSON array element at a given index.
 *
 * Generated by tools/codegen/codegen_nebula.py from the MEOS function
 * `({std::string _s(jsonPtr,jsonSize);text* _js=json_in(_s.c_str());if(!_js)return 0u;text* _res=json_array_element_text(_js,(int)idx);free(_js);_res;})`. Per-event scalar operator following the
 * TemporalEDWithinGeometry pattern.
 */
class JsonArrayElementTextLogicalFunction : public LogicalFunctionConcept {
public:
    static constexpr std::string_view NAME = "JsonArrayElementText";

    JsonArrayElementTextLogicalFunction(LogicalFunction json,
                                          LogicalFunction idx);

    DataType getDataType() const override;
    LogicalFunction withDataType(const DataType& dataType) const override;
    std::vector<LogicalFunction> getChildren() const override;
    LogicalFunction withChildren(const std::vector<LogicalFunction>& children) const override;
    std::string_view getType() const override;
    bool operator==(const LogicalFunctionConcept& rhs) const override;
    std::string explain(ExplainVerbosity verbosity) const override;
    LogicalFunction withInferredDataType(const Schema& schema) const override;
    SerializableFunction serialize() const override;

private:
    DataType dataType;
    std::vector<LogicalFunction> parameters;
};

} // namespace NES
