/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Functions/LogicalFunction.hpp>
#include <string_view>
#include <utility>
#include <vector>

namespace NES {

/**
 * @brief Nearest-approach distance for a tpcpoint instant and a geometry.
 *
 * Generated by tools/codegen/codegen_nebula.py from the MEOS function
 * `({char* _hs=(char*)malloc(pt_hexwkbSize+1);if(!_hs)return 0.0;memcpy(_hs,pt_hexwkbPtr,pt_hexwkbSize);_hs[pt_hexwkbSize]='\0';Pcpoint* _pt=pcpoint_from_hexwkb(_hs);free(_hs);if(!_pt)return 0.0;TInstant* _inst=tpointcloudinst_make(_pt,(TimestampTz)ts);free(_pt);if(!_inst)return 0.0;char* _gs_str=(char*)malloc(tgt_wktSize+1);if(!_gs_str){free(_inst);return 0.0;}memcpy(_gs_str,tgt_wktPtr,tgt_wktSize);_gs_str[tgt_wktSize]='\0';GSERIALIZED* _gs=geom_in(_gs_str,-1);free(_gs_str);if(!_gs){free(_inst);return 0.0;}double _r=nad_tpcpoint_geo((Temporal*)_inst,_gs);free(_inst);free(_gs);_r;})`. Per-event scalar operator following the
 * TemporalEDWithinGeometry pattern.
 */
class NadTpcpointGeoLogicalFunction : public LogicalFunctionConcept {
public:
    static constexpr std::string_view NAME = "NadTpcpointGeo";

    NadTpcpointGeoLogicalFunction(LogicalFunction pt_hexwkb,
                                          LogicalFunction ts,
                                          LogicalFunction tgt_wkt);

    DataType getDataType() const override;
    LogicalFunction withDataType(const DataType& dataType) const override;
    std::vector<LogicalFunction> getChildren() const override;
    LogicalFunction withChildren(const std::vector<LogicalFunction>& children) const override;
    std::string_view getType() const override;
    bool operator==(const LogicalFunctionConcept& rhs) const override;
    std::string explain(ExplainVerbosity verbosity) const override;
    LogicalFunction withInferredDataType(const Schema& schema) const override;
    SerializableFunction serialize() const override;

private:
    DataType dataType;
    std::vector<LogicalFunction> parameters;
};

} // namespace NES
